Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2020-11, with the labels that each got.

#148 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#149 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#150 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#151 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#154 Test with k8s 17, 18 and 19. Use 18.4 for eventing.
  .github/workflows/kind-e2e.yaml
  test/kind/prerequisites.sh
Labels: approved, cla: yes, lgtm, size/M

#157 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#159 exercise more eventing-versions
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#152 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#161 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/recordevents/sender/sender.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#165 update to rabbitmq cluster operator 1.0.0
  .github/workflows/kind-e2e.yaml
  pkg/apis/duck/v1beta1/rabbit.go
  pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/broker/broker_config.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#164 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#166 Update version requirement, refactor docs
  broker/README.md
Labels: approved, cla: yes, lgtm, size/L

#171 Fix deadlock, logging and message handling
  cmd/dispatcher/main.go
  go.mod
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  vendor/modules.txt
Labels: approved, cla: yes, kind/bug, lgtm, size/L

#167 upgrade to latest dependencies, fix trigger_test
  go.mod
  go.sum
  pkg/reconciler/trigger/trigger_test.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1beta2/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta2/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta2/pingsource.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#168 [Automated] Format markdown
  broker/README.md
Labels: approved, cla: yes, lgtm, size/S

#169 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/k8s/events.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#172 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
