Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2020-09, with the labels that each got.

#12 fix the ut tests so they pass
  source/pkg/adapter/adapter_test.go
  source/pkg/apis/sources/v1alpha1/rabbitmq_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/S

#14 Adding Rigging for e2e tests.
  .github/workflows/go-pr-build.yaml
  .github/workflows/go-pr-style.yaml
  .github/workflows/go-pr-test.yaml
  .github/workflows/go-pr-verify.yaml
  .github/workflows/kind-e2e.yaml
  test/config/config-logging.yaml
  test/config/quacken.yaml
  test/e2e/config/rabbitmq/cluster.yaml
  test/e2e/config/smoke/broker/smoke.yaml
  test/e2e/main_test.go
  test/e2e/smoke_test.go
  test/kind/README.md
  test/kind/bootstrap.sh
  test/kind/install.sh
  test/kind/run-tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#15 fix codegen
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/S

#16 Rigging: adding missing files.
  go.mod
  go.sum
  vendor/github.com/n3wscott/rigging/.gitignore
  vendor/github.com/n3wscott/rigging/AUTHORS
  vendor/github.com/n3wscott/rigging/Gopkg.lock
  vendor/github.com/n3wscott/rigging/Gopkg.toml
  vendor/github.com/n3wscott/rigging/LICENSE
  vendor/github.com/n3wscott/rigging/README.md
  vendor/github.com/n3wscott/rigging/pkg/images/cmd.go
  vendor/github.com/n3wscott/rigging/pkg/images/ko.go
  vendor/github.com/n3wscott/rigging/pkg/installer/images.go
  vendor/github.com/n3wscott/rigging/pkg/installer/templates.go
  vendor/github.com/n3wscott/rigging/pkg/lifecycle/job.go
  vendor/github.com/n3wscott/rigging/pkg/lifecycle/lifecycle.go
  vendor/github.com/n3wscott/rigging/pkg/lifecycle/pod.go
  vendor/github.com/n3wscott/rigging/pkg/manifest/manifest.go
  vendor/github.com/n3wscott/rigging/pkg/manifest/yaml.go
  vendor/github.com/n3wscott/rigging/rigging.go
  vendor/knative.dev/pkg/ptr/doc.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/knative.dev/pkg/test/logstream/doc.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/test/logstream/null.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#17 gofmt
  pkg/internal/thirdparty/keda/client/clientset/versioned/clientset.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/fake/clientset_generated.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/fake/register.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/scheme/register.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_keda_client.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_scaledobject.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_triggerauthentication.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/typed/keda/v1alpha1/keda_client.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/typed/keda/v1alpha1/scaledobject.go
  pkg/internal/thirdparty/keda/client/clientset/versioned/typed/keda/v1alpha1/triggerauthentication.go
  pkg/internal/thirdparty/keda/client/informers/externalversions/factory.go
  pkg/internal/thirdparty/keda/client/informers/externalversions/generic.go
  pkg/internal/thirdparty/keda/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/internal/thirdparty/keda/client/informers/externalversions/keda/v1alpha1/scaledobject.go
  pkg/internal/thirdparty/keda/client/informers/externalversions/keda/v1alpha1/triggerauthentication.go
  pkg/internal/thirdparty/keda/client/injection/client/client.go
  pkg/internal/thirdparty/keda/client/injection/client/fake/fake.go
  pkg/internal/thirdparty/keda/client/listers/keda/v1alpha1/scaledobject.go
  pkg/internal/thirdparty/keda/client/listers/keda/v1alpha1/triggerauthentication.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/broker/resources/triggerauthentication.go
  pkg/reconciler/internal/testrabbit/rabbit_container.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/resources/scaled_object.go
Labels: approved, cla: yes, lgtm, size/M

#22 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/LICENSE
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#24 adding n3wscott to owners.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#25 address pr feedback
  cmd/webhook/main.go
  config/source/500-webhook-config-validation.yaml
  config/source/500-webhook-defaulting.yaml
  config/source/500-webhook-resource-validation.yaml
Labels: approved, cla: yes, lgtm, size/S

#28 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/LICENSE
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#21 [master] golang format tools
  pkg/adapter/adapter.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
  pkg/apis/sources/v1alpha1/register_test.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/internal/testrabbit/rabbit_container.go
  pkg/reconciler/source/controller.go
  pkg/reconciler/source/resources/labels_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  pkg/reconciler/trigger/resources/queue.go
  test/e2e/smoke_test.go
Labels: approved, cla: yes, lgtm, size/M

#19 [master] Format markdown
  README.md
  broker/README.md
  source/README.md
  test/kind/README.md
Labels: approved, cla: yes, lgtm, size/XL

#26 fix copyright years. follow up to 23
  config/source/201-webhook-serviceaccount.yaml
  config/source/400-webhook-service.yaml
  config/source/500-webhook-config-validation.yaml
  config/source/500-webhook-defaulting.yaml
  config/source/500-webhook-resource-validation.yaml
  config/source/500-webhook-secret.yaml
  config/source/500-webhook-sinkbindings.yaml
  config/source/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#30 remove one off actions
  .github/workflows/go-pr-build.yaml
  .github/workflows/go-pr-style.yaml
  .github/workflows/go-pr-test.yaml
  .github/workflows/go-pr-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#27 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#29 e2e tests run, but fail.
  .github/workflows/kind-e2e.yaml
  config/config/500-broker-controller.yaml
  test/e2e/smoke_test.go
  test/kind/README.md
  test/kind/install.sh
  test/kind/prerequisites.sh
Labels: approved, cla: yes, lgtm, size/L

#31 drop the go files in third_party
  hack/update-deps.sh
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/pathdriver/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  third_party/VENDOR-LICENSE/github.com/lightstep/tracecontext.go/LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#33 [master] Fix spelling errors
  pkg/apis/duck/v1beta1/rabbit.go
Labels: approved, cla: yes, lgtm, size/XS

#34 [master] Update GitHub Actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#35 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/LICENSE
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#37 Broker reconciler now makes a secret based on the config it points to
  broker/README.md
  go.sum
  hack/update-codegen.sh
  pkg/apis/apis.go
  pkg/apis/duck/v1beta1/rabbit.go
  pkg/apis/duck/v1beta1/register.go
  pkg/apis/duck/v1beta1/register_test.go
  pkg/apis/sources/group.go
  pkg/apis/sources/register.go
  pkg/apis/sources/v1alpha1/doc.go
  pkg/apis/sources/v1alpha1/register.go
  pkg/client/injection/ducks/duck/v1beta1/rabbit/fake/fake.go
  pkg/client/injection/ducks/duck/v1beta1/rabbit/rabbit.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_config.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/broker/resources/secret.go
  pkg/reconciler/internal/testrabbit/rabbit_container.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/trigger.go
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/pathdriver/LICENSE
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#38 Add linting config and fix issues.
  .golangci.yaml
  cmd/ingress/main.go
  pkg/adapter/adapter_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_lifecycle_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/source/controller.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/resources/scaled_object.go
  pkg/reconciler/trigger/trigger.go
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/LICENSE
Labels: approved, cla: yes, lgtm, size/M

#41 Point to a broker
  .github/workflows/kind-e2e.yaml
  config/config/200-rabbitmq-broker-clusterrole.yaml
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_config.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/trigger/trigger.go
  test/e2e/config/smoke/broker/smoke.yaml
  test/e2e/smoke_test.go
  test/kind/prerequisites.sh
Labels: approved, cla: yes, lgtm, size/L

#42 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#44 only reconcile my own triggers
  pkg/reconciler/broker/broker.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#45 update deps
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/duck/subscriber.go
  vendor/knative.dev/eventing/pkg/logging/logging.go
  vendor/knative.dev/eventing/pkg/utils/cache/persisted_store.go
  vendor/knative.dev/eventing/pkg/utils/headers.go
  vendor/knative.dev/eventing/test/lib/config.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/eventing/test/lib/duck/serving_checks.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/send_event.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/performance/infra/aggregator/aggregator.go
  vendor/knative.dev/eventing/test/performance/infra/image_helpers.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#46 Revert "update deps"
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/duck/subscriber.go
  vendor/knative.dev/eventing/pkg/logging/logging.go
  vendor/knative.dev/eventing/pkg/utils/cache/persisted_store.go
  vendor/knative.dev/eventing/pkg/utils/headers.go
  vendor/knative.dev/eventing/test/lib/config.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/eventing/test/lib/duck/serving_checks.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/send_event.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/performance/infra/aggregator/aggregator.go
  vendor/knative.dev/eventing/test/performance/infra/image_helpers.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#47 fix the codes
  pkg/reconciler/broker/broker_config.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/XS

#49 move broker config files to better location
  broker/README.md
  config/broker/200-rabbitmq-broker-binding.yaml
  config/broker/200-rabbitmq-broker-clusterrole.yaml
  config/broker/500-broker-controller.yaml
Labels: approved, cla: yes, lgtm, size/S

#50 have one replica for dispatcher until we get keda back up
  pkg/reconciler/trigger/resources/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#51 I forgot to install this repo in the e2e test in github actions
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#56 use checked in packages
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#53 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#54 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/LICENSE
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/honnef.co/go/tools/pattern/match.go
  vendor/honnef.co/go/tools/staticcheck/lint.go
  vendor/honnef.co/go/tools/version/version.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#57 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#58 remove direct keda dependency, move it to knattive-autoscaler-keda
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/resources/triggerauthentication.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/resources/scaled_object.go
  pkg/reconciler/trigger/trigger.go
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/pathdriver/LICENSE
  third_party/VENDOR-LICENSE/github.com/kedacore/keda/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/eventing-autoscaler-keda/pkg/client/injection/keda/LICENSE
  third_party/VENDOR-LICENSE/sigs.k8s.io/controller-runtime/pkg/scheme/LICENSE
  vendor/github.com/kedacore/keda/LICENSE
  vendor/github.com/kedacore/keda/api/v1alpha1/condition_types.go
  vendor/github.com/kedacore/keda/api/v1alpha1/groupversion_info.go
  vendor/github.com/kedacore/keda/api/v1alpha1/gvkr_types.go
  vendor/github.com/kedacore/keda/api/v1alpha1/scaledjob_types.go
  vendor/github.com/kedacore/keda/api/v1alpha1/scaledobject_types.go
  vendor/github.com/kedacore/keda/api/v1alpha1/triggerauthentication_types.go
  vendor/github.com/kedacore/keda/api/v1alpha1/withtriggers_types.go
  vendor/github.com/kedacore/keda/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/clientset.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/doc.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/scheme/doc.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/typed/keda/v1alpha1/doc.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/typed/keda/v1alpha1/generated_expansion.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/typed/keda/v1alpha1/keda_client.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/typed/keda/v1alpha1/scaledjob.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/typed/keda/v1alpha1/scaledobject.go
  vendor/github.com/kedacore/keda/pkg/generated/clientset/versioned/typed/keda/v1alpha1/triggerauthentication.go
  vendor/github.com/kedacore/keda/pkg/generated/informers/externalversions/factory.go
  vendor/github.com/kedacore/keda/pkg/generated/informers/externalversions/generic.go
  vendor/github.com/kedacore/keda/pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/kedacore/keda/pkg/generated/informers/externalversions/keda/interface.go
  vendor/github.com/kedacore/keda/pkg/generated/informers/externalversions/keda/v1alpha1/interface.go
  vendor/github.com/kedacore/keda/pkg/generated/informers/externalversions/keda/v1alpha1/scaledjob.go
  vendor/github.com/kedacore/keda/pkg/generated/informers/externalversions/keda/v1alpha1/scaledobject.go
  vendor/github.com/kedacore/keda/pkg/generated/informers/externalversions/keda/v1alpha1/triggerauthentication.go
  vendor/github.com/kedacore/keda/pkg/generated/listers/keda/v1alpha1/expansion_generated.go
  vendor/github.com/kedacore/keda/pkg/generated/listers/keda/v1alpha1/scaledjob.go
  vendor/github.com/kedacore/keda/pkg/generated/listers/keda/v1alpha1/scaledobject.go
  vendor/github.com/kedacore/keda/pkg/generated/listers/keda/v1alpha1/triggerauthentication.go
  vendor/knative.dev/eventing-autoscaler-keda/LICENSE
  vendor/knative.dev/eventing-autoscaler-keda/pkg/client/injection/keda/client/client.go
  vendor/knative.dev/eventing-autoscaler-keda/pkg/client/injection/keda/informers/factory/factory.go
  vendor/knative.dev/eventing-autoscaler-keda/pkg/client/injection/keda/informers/keda/v1alpha1/scaledobject/scaledobject.go
  vendor/knative.dev/eventing-autoscaler-keda/pkg/client/injection/keda/informers/keda/v1alpha1/triggerauthentication/triggerauthentication.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/scheme/scheme.go
Labels: approved, cla: yes, lgtm, size/XXL

#59 [master] Auto-update dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/LICENSE
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#60 add test/presubmit-tests.sh to let the nightly releases to work
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#62 consistent queue names, v1.Trigger
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/resources/binding.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/trigger.go
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/pathdriver/LICENSE
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1/broker/broker.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1/trigger/trigger.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/state.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#64 enable code coverage
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
  go.mod
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/testrabbit/rabbit_container.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/queue_test.go
  third_party/VENDOR-LICENSE/github.com/containerd/continuity/LICENSE
  vendor/github.com/containerd/continuity/.gitignore
  vendor/github.com/containerd/continuity/.mailmap
  vendor/github.com/containerd/continuity/.travis.yml
  vendor/github.com/containerd/continuity/Makefile
  vendor/github.com/containerd/continuity/README.md
  vendor/github.com/containerd/continuity/context.go
  vendor/github.com/containerd/continuity/devices/devices.go
  vendor/github.com/containerd/continuity/devices/devices_unix.go
  vendor/github.com/containerd/continuity/devices/devices_windows.go
  vendor/github.com/containerd/continuity/digests.go
  vendor/github.com/containerd/continuity/driver/driver.go
  vendor/github.com/containerd/continuity/driver/driver_unix.go
  vendor/github.com/containerd/continuity/driver/driver_windows.go
  vendor/github.com/containerd/continuity/driver/lchmod_linux.go
  vendor/github.com/containerd/continuity/driver/lchmod_unix.go
  vendor/github.com/containerd/continuity/driver/utils.go
  vendor/github.com/containerd/continuity/go.mod
  vendor/github.com/containerd/continuity/go.sum
  vendor/github.com/containerd/continuity/groups_unix.go
  vendor/github.com/containerd/continuity/hardlinks.go
  vendor/github.com/containerd/continuity/hardlinks_unix.go
  vendor/github.com/containerd/continuity/hardlinks_windows.go
  vendor/github.com/containerd/continuity/ioutils.go
  vendor/github.com/containerd/continuity/manifest.go
  vendor/github.com/containerd/continuity/proto/gen.go
  vendor/github.com/containerd/continuity/proto/manifest.pb.go
  vendor/github.com/containerd/continuity/proto/manifest.proto
  vendor/github.com/containerd/continuity/resource.go
  vendor/github.com/containerd/continuity/resource_unix.go
  vendor/github.com/containerd/continuity/resource_windows.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#63 remove now unused function
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/S

#69 config moved. fix release label
  config/broker/200-rabbitmq-broker-binding.yaml
  config/broker/200-rabbitmq-broker-clusterrole.yaml
  config/broker/500-broker-controller.yaml
  config/source/100-namespace.yaml
  config/source/200-serviceaccount.yaml
  config/source/200-webhook-clusterrole.yaml
  config/source/201-clusterrole.yaml
  config/source/201-webhook-serviceaccount.yaml
  config/source/202-clusterrolebinding.yaml
  config/source/300-rabbitmqsource.yaml
  config/source/400-controller-service.yaml
  config/source/400-webhook-service.yaml
  config/source/500-controller.yaml
  config/source/500-webhook-config-validation.yaml
  config/source/500-webhook-defaulting.yaml
  config/source/500-webhook-resource-validation.yaml
  config/source/500-webhook-secret.yaml
  config/source/500-webhook-sinkbindings.yaml
  config/source/500-webhook.yaml
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M

#68 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/go/analysis/validate.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#67 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#72 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#79 point to KEDA, add a link to ko
  broker/README.md
Labels: approved, cla: yes, lgtm, size/XS

#85 [Release] Pin upstreams for release 0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#86 more ut
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#82 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#87 more coverage
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/broker_test_helper.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#83 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go
  vendor/knative.dev/eventing/pkg/tracing/setup.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#88 Leverage new release artifacts of rabbitmq-operator
  .github/workflows/kind-e2e.yaml
  test/kind/prerequisites.sh
Labels: approved, cla: yes, lgtm, size/M

#91 adding badges and nightly links
  README.md
Labels: approved, cla: yes, lgtm, size/S

#89 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#90 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#92 [Automated] Format markdown
  broker/README.md
Labels: approved, cla: yes, lgtm, size/XS

#93 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#95 eventing-rabbitmq has no dep on serving.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#98 use utils in knative/pkg
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/S
