Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-09, with the labels that each got.

#390 Update broker ref to v1
  broker/README.md
Labels: cla: yes, approved, size/XS, lgtm

#394 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#398 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#400 [release-0.25] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#402 drop scheduled actions these fill up the job queue causing delays
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, approved, size/XS, lgtm

#403 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#404 [release-0.24] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#405 [release-0.23] Upgrade to latest dependencies
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#406 [release-0.22] Upgrade to latest dependencies
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#417 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#419 Update deps
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/state.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/state.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/state.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#422 Bump eventing and cert-manager
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, approved, lgtm, size/S

#421 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/S

#420 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#407 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#428 bump ko to 0.9.1
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, approved, size/XS, lgtm

#429 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/S

#430 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, size/XS, lgtm

#433 Switch broker DLQ test to use a k8s Service
  pkg/reconciler/broker/broker_test.go
Labels: cla: yes, approved, size/XS, lgtm

#434 Switch broker DLQ test to use a k8s Service (again)
  pkg/reconciler/brokerstandalone/broker_test.go
Labels: cla: yes, approved, size/XS, lgtm

#431 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#435 Vhost source readme
  source/README.adoc
  test/e2e/config/rabbitmqvhost/clustervhost.yaml
Labels: cla: yes, approved, size/XS, lgtm

#436 Wabbit and amqp updates
  cmd/dispatcher/main.go
  cmd/ingress/main.go
  go.mod
  go.sum
  pkg/adapter/adapter_test.go
  pkg/dispatcher/dispatcher.go
  pkg/reconciler/brokerstandalone/resources/exchange.go
  pkg/reconciler/io/closers.go
  pkg/reconciler/triggerstandalone/resources/queue.go
  samples/source/example/simple_producer.go
  test/e2e/cmd/rabbitproducer/main.go
  third_party/VENDOR-LICENSE/github.com/rabbitmq/amqp091-go/LICENSE
  vendor/github.com/NeowayLabs/wabbit/README.md
  vendor/github.com/NeowayLabs/wabbit/amqp.go
  vendor/github.com/NeowayLabs/wabbit/amqp/channel.go
  vendor/github.com/NeowayLabs/wabbit/amqp/confirmation.go
  vendor/github.com/NeowayLabs/wabbit/amqp/delivery.go
  vendor/github.com/NeowayLabs/wabbit/amqp/dial.go
  vendor/github.com/NeowayLabs/wabbit/amqp/queue.go
  vendor/github.com/NeowayLabs/wabbit/amqptest/dial.go
  vendor/github.com/NeowayLabs/wabbit/amqptest/server/channel.go
  vendor/github.com/NeowayLabs/wabbit/amqptest/server/delivery.go
  vendor/github.com/NeowayLabs/wabbit/amqptest/server/exchange.go
  vendor/github.com/NeowayLabs/wabbit/amqptest/server/utils.go
  vendor/github.com/NeowayLabs/wabbit/amqptest/server/vhost.go
  vendor/github.com/NeowayLabs/wabbit/utils/opt.go
  vendor/github.com/rabbitmq/amqp091-go/.gitignore
  vendor/github.com/rabbitmq/amqp091-go/.travis.yml
  vendor/github.com/rabbitmq/amqp091-go/CODE_OF_CONDUCT.md
  vendor/github.com/rabbitmq/amqp091-go/CONTRIBUTING.md
  vendor/github.com/rabbitmq/amqp091-go/LICENSE
  vendor/github.com/rabbitmq/amqp091-go/Makefile
  vendor/github.com/rabbitmq/amqp091-go/README.md
  vendor/github.com/rabbitmq/amqp091-go/allocator.go
  vendor/github.com/rabbitmq/amqp091-go/auth.go
  vendor/github.com/rabbitmq/amqp091-go/certs.sh
  vendor/github.com/rabbitmq/amqp091-go/channel.go
  vendor/github.com/rabbitmq/amqp091-go/confirms.go
  vendor/github.com/rabbitmq/amqp091-go/connection.go
  vendor/github.com/rabbitmq/amqp091-go/consumers.go
  vendor/github.com/rabbitmq/amqp091-go/delivery.go
  vendor/github.com/rabbitmq/amqp091-go/doc.go
  vendor/github.com/rabbitmq/amqp091-go/fuzz.go
  vendor/github.com/rabbitmq/amqp091-go/gen.sh
  vendor/github.com/rabbitmq/amqp091-go/go.mod
  vendor/github.com/rabbitmq/amqp091-go/pre-commit
  vendor/github.com/rabbitmq/amqp091-go/read.go
  vendor/github.com/rabbitmq/amqp091-go/return.go
  vendor/github.com/rabbitmq/amqp091-go/spec091.go
  vendor/github.com/rabbitmq/amqp091-go/types.go
  vendor/github.com/rabbitmq/amqp091-go/uri.go
  vendor/github.com/rabbitmq/amqp091-go/write.go
  vendor/github.com/streadway/amqp/go.mod
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XL

#418 Add support for concurrent dispatch and configurable prefetch
  cmd/dispatcher/main.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  test/e2e/config/brokertrigger/broker.yaml
  test/e2e/config/brokertrigger/brokertrigger.go
  test/e2e/config/brokertrigger/producer.yaml
  test/e2e/config/brokertrigger/trigger.yaml
  test/e2e/config/direct/trigger.yaml
  test/e2e/direct_test.go
  test/e2e/dispatcher_test.go
  test/e2e/recorder.go
Labels: cla: yes, approved, lgtm, size/XL, kind/enhancement

#432 Use latest versions in operator docs
  broker/operator-based.md
Labels: cla: yes, approved, lgtm, size/M, kind/documentation

#441 Simplify backoff delay default
  cmd/dispatcher/main.go
Labels: cla: yes, approved, lgtm, size/S, kind/cleanup
