Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-12, with the labels that each got.

#531 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#515 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/eventing/pkg/utils/headers.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XL

#529 Docs: explain how to run/debug e2e tests
  test/e2e/README.md
Labels: cla: yes, approved, lgtm, size/S, kind/documentation

#532 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#538 Fix rekt compile errors
  go.mod
  go.sum
  test/e2e/smoke_test_broker_trigger.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#542 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#549 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#547 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#530 Remove ineffectual ctx assignment
  pkg/dispatcher/dispatcher.go
Labels: cla: yes, approved, size/XS, lgtm

#370 Add tracing support to dispatcher and ingress
  cmd/controller/broker/main.go
  cmd/controller/brokerstandalone/main.go
  cmd/dispatcher/main.go
  cmd/ingress/main.go
  go.mod
  pkg/dispatcher/dispatcher.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/brokerstandalone/broker.go
  pkg/reconciler/brokerstandalone/controller.go
  pkg/reconciler/brokerstandalone/controller_test.go
  pkg/reconciler/brokerstandalone/resources/dispatcher.go
  pkg/reconciler/brokerstandalone/resources/ingress.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/controller_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/triggerstandalone/controller.go
  pkg/reconciler/triggerstandalone/controller_test.go
  pkg/reconciler/triggerstandalone/resources/dispatcher.go
  pkg/reconciler/triggerstandalone/trigger.go
  pkg/utils/envconfig.go
  pkg/utils/filter.go
  samples/tracing/100-ns.yaml
  samples/tracing/README.md
  samples/tracing/broker.yaml
  samples/tracing/cluster.yaml
  samples/tracing/sink.yaml
  samples/tracing/source.yaml
  samples/tracing/trigger.yaml
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/modules.txt
Labels: cla: yes, approved, size/XXL, lgtm, kind/enhancement

#548 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/XL

#551 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#536 Source adapter trigger dispatcher homologation
  cmd/dispatcher/main.go
  pkg/adapter/adapter.go
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/dispatcher/dispatcher.go
  samples/broker-trigger/README.md
  samples/source/500-source.yaml
  source/README.adoc
Labels: cla: yes, approved, lgtm, size/L, kind/enhancement

#525 Setup local host & run end-to-end tests with a single command
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  .gitignore
  Makefile
  test/e2e/kind.yaml
  test/kind/README.md
  test/kind/bootstrap.sh
  test/kind/install.sh
  test/kind/prerequisites.sh
  test/kind/run-tests.sh
Labels: cla: yes, approved, size/XXL, lgtm, kind/cleanup

#554 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#541 Add securityContext to Knative Eventing RabbitMQ objects
  config/broker/500-broker-controller.yaml
  config/broker/500-webhook.yaml
  config/brokerstandalone/500-broker-controller.yaml
  config/brokerstandalone/500-webhook.yaml
  config/source/500-controller.yaml
  config/source/500-webhook.yaml
Labels: approved, lgtm, size/M
