Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-04, with the labels that each got.

#268 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/ingress.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/data_plane.go
  vendor/knative.dev/eventing/test/rekt/resources/addressable/addressable.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L

#270 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/conformance/LICENSE
  vendor/github.com/cloudevents/conformance/pkg/event/event.go
  vendor/github.com/cloudevents/conformance/pkg/event/read.go
  vendor/github.com/cloudevents/conformance/pkg/event/write.go
  vendor/github.com/cloudevents/conformance/pkg/http/http.go
  vendor/github.com/cloudevents/conformance/pkg/http/raw.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/LICENSE
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/observability_service.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/observable.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/reporter.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/trace_attributes.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/http/http.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/pkg/network/domain.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#272 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/state.go
  third_party/VENDOR-LICENSE/github.com/cloudevents/conformance/pkg/event/LICENSE
  third_party/VENDOR-LICENSE/github.com/pmezard/go-difflib/difflib/LICENSE
  third_party/VENDOR-LICENSE/github.com/stretchr/testify/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/LICENSE
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/state.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/state.go
  vendor/knative.dev/eventing/test/performance/infra/aggregator/aggregator.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/knative.dev/eventing/test/performance/infra/sender/http_load_generator.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/data_plane.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/reconciler-test/cmd/eventshub/main.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/dropevents/dropeventsfibonacci/fibonacci.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/dropevents/dropeventsfirst/sequence.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/dropevents/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_log.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/logger_vent/logger.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/reply.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/constructor.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/doc.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/recorder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/resources/svc/service.go
  vendor/knative.dev/reconciler-test/resources/svc/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#274 test only with 1.6 of rabbit op
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#271 Use CRDs instead of client libraries with RabbitMQ cluster operator
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  config/broker/200-rabbitmq-broker-clusterrole.yaml
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/broker/resources/ingress_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/controller_test.go
  pkg/reconciler/trigger/resources/binding.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XL

#277 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
Labels: approved, cla: yes, lgtm, size/L
