Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-01, with the labels that each got.

#184 Fix ko setup
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#185 Disable servicelinks at webhook yaml
  config/source/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#178 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#187 [Automated] Format markdown
  source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#188 Continuous tests
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#190 trying to fix e2e
  .github/workflows/kind-e2e.yaml
  test/e2e/recorder.go
  test/kind/run-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#193 update deps to release 0.20
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#194 test e2e with eventing v0.20.0
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#196 use go 1.15 on kind e2e
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#195 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/pkg/kncloudevents/populate_span_transformer.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#197 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#198 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#199 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#203 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#202 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/S

#204 add more rabbitmq cluster operator versions
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#205 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#206 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/duck/channel.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#208 [] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/sources/v1alpha1/rabbitmqsource/filtered/fake/fake.go
  pkg/client/injection/informers/sources/v1alpha1/rabbitmqsource/filtered/rabbitmqsource.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#209 use hack scripts to wait for pod readiness
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#210 update the copy&paste commands to reflect reality
  cmd/failer/main.go
Labels: approved, cla: yes, lgtm, size/S

#207 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#212 [release-0.19] cp 165, update ko install
  .github/workflows/kind-e2e.yaml
  pkg/apis/duck/v1beta1/rabbit.go
  pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/broker/broker_config.go
  test/e2e/cmd/producer/main.go
  test/e2e/config/direct/producer.yaml
  test/e2e/config/dlq/producer.yaml
  test/e2e/config/rabbitmq/cluster.yaml
Labels: approved, cla: yes, lgtm, size/L

#214 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#216 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/step.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#215 bump to go 1.15
  go.mod
Labels: approved, cla: yes, lgtm, size/XS

#201 Implement best-practice Source documentation
  source/DEVELOPMENT.md
  source/README.adoc
Labels: approved, cla: yes, kind/documentation, lgtm, size/L
