Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-07, with the labels that each got.

#357 Vhost test fixes
  test/e2e/config/vhostsourceproducer/vhost-producer.yaml
  test/e2e/config/vhostsourceproducer/vhostsourceproducer.go
  test/e2e/sourcevhost_test.go
Labels: approved, cla: yes, lgtm, size/M

#355 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#359 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#361 fix deprecated methods
  cmd/failer/main.go
  pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#362 use source.StatsReporter from knative.dev/eventing
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#365 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#364 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#368 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
