Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-06, with the labels that each got.

#321 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/conditions/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/source/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/source/source.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#327 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#322 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#323 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#325 Fix issue #320
  broker/standalone.md
Labels: approved, cla: yes, lgtm, size/XS

#330 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#331 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#326 added vhost capabilities to rabbitmq source + tests
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
Labels: approved, cla: yes, kind/feature-request, lgtm, size/M

#333 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#335 Update Knative dependency for release-0.23
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#336 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#339 Update drawing
  broker/rabbitmq-knative-broker.png
Labels: approved, cla: yes, lgtm, size/XS

#337 Trigger dlq
  go.mod
  go.sum
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/broker/resources/ingress_test.go
  pkg/reconciler/brokerstandalone/broker_test.go
  pkg/reconciler/testrabbit/rabbit_container.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/controller_test.go
  pkg/reconciler/trigger/resources/binding.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/reconciler/triggerstandalone/resources/binding.go
  pkg/reconciler/triggerstandalone/trigger_test.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#340 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/scheme/scheme.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#342 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#341 Add support for Trigger DeadLetterSink for Standalone Broker.
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/brokerstandalone/broker_test.go
  pkg/reconciler/brokerstandalone/resources/exchange.go
  pkg/reconciler/brokerstandalone/resources/exchange_test.go
  pkg/reconciler/brokerstandalone/resources/ingress_test.go
  pkg/reconciler/trigger/resources/binding.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/triggerstandalone/resources/binding.go
  pkg/reconciler/triggerstandalone/resources/binding_test.go
  pkg/reconciler/triggerstandalone/resources/dispatcher.go
  pkg/reconciler/triggerstandalone/resources/dispatcher_test.go
  pkg/reconciler/triggerstandalone/resources/queue.go
  pkg/reconciler/triggerstandalone/resources/queue_test.go
  pkg/reconciler/triggerstandalone/trigger.go
  pkg/reconciler/triggerstandalone/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#344 Rabbitmq resource naming
  pkg/rabbitmqnaming/naming.go
  pkg/rabbitmqnaming/naming_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/ingress_test.go
  pkg/reconciler/brokerstandalone/broker.go
  pkg/reconciler/brokerstandalone/broker_test.go
  pkg/reconciler/brokerstandalone/resources/exchange.go
  pkg/reconciler/brokerstandalone/resources/exchange_test.go
  pkg/reconciler/brokerstandalone/resources/ingress.go
  pkg/reconciler/brokerstandalone/resources/ingress_test.go
  pkg/reconciler/trigger/resources/binding.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/reconciler/triggerstandalone/resources/binding.go
  pkg/reconciler/triggerstandalone/resources/binding_test.go
  pkg/reconciler/triggerstandalone/resources/dispatcher_test.go
  pkg/reconciler/triggerstandalone/resources/queue.go
  pkg/reconciler/triggerstandalone/resources/queue_test.go
  pkg/reconciler/triggerstandalone/trigger.go
  pkg/reconciler/triggerstandalone/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XL

#346 Fix the lints from 344
  pkg/rabbitmqnaming/naming_test.go
  pkg/reconciler/brokerstandalone/resources/exchange_test.go
  pkg/reconciler/triggerstandalone/resources/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/S

#345 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.go
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#348 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#350 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#352 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#353 changed tests version to pass the github workflows
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/M
