Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-05, with the labels that each got.

#279 use delivery spec of trigger and if not set, do not retry
  .github/workflows/kind-conformance.yaml
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  test/conformance/conformance_test.go
Labels: approved, cla: yes, lgtm, size/XS

#280 rework the ingress of broker for rabbit
  cmd/ingress/main.go
  test/conformance/main_test.go
Labels: approved, cla: yes, lgtm, size/L

#282 do not warn if conn is already closed, normal
  cmd/dispatcher/main.go
Labels: approved, cla: yes, lgtm, size/XS

#283 hoist rabbitmqcluster into proper prereq (fix conformance tests)
  test/conformance/conformance_test.go
  test/conformance/features/rabbitmqcluster/readyness.go
  test/conformance/resources/rabbitmqcluster/rabbbitmqcluster.yaml
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.go
Labels: approved, cla: yes, lgtm, size/M

#284 now that tests are fixed, drop timeout to 20m
  .github/workflows/kind-conformance.yaml
Labels: approved, cla: yes, lgtm, size/XS

#286 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#290 Bump to go 1.16
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  go.mod
Labels: approved, cla: yes, lgtm, size/S

#292 Add UT. Clean resource creation logic
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/trigger/resources/binding.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XL

#293 Crd ut 2
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_config.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/broker_test_helper.go
Labels: approved, cla: yes, lgtm, size/L

#296 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#299 Add more UT for fails
  go.sum
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_config.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/L

#289 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#291 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#302 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#301 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#303 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#305 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#306 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscribable_channelable_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#308 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#312 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#311 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#314 fix the lint by adding test that I was planning on adding
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#315 Update docs
  README.md
  broker/README.md
  broker/operator-based.md
  broker/standalone.md
  hack/release.sh
  samples/broker/dlq/README.md
  samples/source/event-display.yaml
Labels: approved, cla: yes, lgtm, size/L

#313 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/knative.dev/reconciler-test/resources/svc/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#318 test with eventing .23
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#319 remove unnecessary keda permissions
  config/broker/200-rabbitmq-broker-clusterrole.yaml
  config/brokerstandalone/200-rabbitmq-broker-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M
