Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-11, with the labels that each got.

#481 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#480 Add Rabbitmq's CloudEvents Protocol Binding Spec to the repo
  cloudevents-protocol-spec/spec.md
  source/README.adoc
Labels: cla: yes, approved, lgtm, size/L

#482 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#483 Document maturity levels in sandbox
  README.md
Labels: cla: yes, approved, size/XS, lgtm

#486 Use retry logic from kncloudevents
  pkg/dispatcher/dispatcher.go
Labels: cla: yes, approved, size/XS, lgtm, kind/bug

#497 Fix link in CE Protocol Spec
  cloudevents-protocol-spec/spec.md
Labels: cla: yes, approved, size/XS, lgtm

#494 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#488 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#493 Add predeclared behavior in RMQ Source
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  source/README.adoc
Labels: cla: yes, approved, lgtm, size/M, kind/enhancement

#501 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/trigger_sink_resolution.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#502 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#444 Update test kind prerequisite instructions
  test/kind/prerequisites.sh
Labels: cla: yes, approved, lgtm, size/S

#475 Spec based msg formating implementation
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/adapter/message.go
  pkg/adapter/message_test.go
  test/e2e/cmd/rabbitproducer/main.go
  test/e2e/config/sourceproducer/sourceproducer.go
  test/e2e/config/vhostsourceproducer/vhostsourceproducer.go
  test/e2e/source_test.go
  test/e2e/sourcevhost_test.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_binary_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_structured_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_transformer.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_unknown_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/transformer.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XL

#503 Added content-type header details to spec, fixed examples and broken index links
  cloudevents-protocol-spec/spec.md
Labels: cla: yes, approved, lgtm, size/M

#514 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#505 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#509 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#498 Sink URI resolver tests update
  pkg/reconciler/testing/factory.go
  pkg/reconciler/trigger/controller_test.go
  pkg/reconciler/triggerstandalone/controller_test.go
Labels: cla: yes, approved, size/XS, lgtm

#512 Hardcode broker class that the broker operates on
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/brokerstandalone/controller.go
  pkg/reconciler/trigger/controller.go
Labels: cla: yes, approved, lgtm, size/M, kind/removal

#490 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/M

#521 Add issue templates from knative/eventing
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: cla: yes, approved, lgtm, size/M

#524 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#527 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, size/XS, lgtm
