Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-08, with the labels that each got.

#372 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#373 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/S

#374 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#376 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/sources/v1alpha1/rabbitmqsource/filtered/rabbitmqsource.go
  pkg/client/injection/informers/sources/v1alpha1/rabbitmqsource/rabbitmqsource.go
  third_party/pkg/client/injection/client/client.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/binding/binding.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/binding/filtered/binding.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/exchange/exchange.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/exchange/filtered/exchange.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/permission/filtered/permission.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/permission/permission.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/policy/filtered/policy.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/policy/policy.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/queue/filtered/queue.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/queue/queue.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/schemareplication/filtered/schemareplication.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/schemareplication/schemareplication.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/user/filtered/user.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/user/user.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/vhost/filtered/vhost.go
  third_party/pkg/client/injection/informers/rabbitmq.com/v1beta1/vhost/vhost.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, size/XXL, lgtm

#380 Bump eventing, update trigger DeadLetterSinkURI
  go.mod
  go.sum
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/triggerstandalone/trigger.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1/broker/broker.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1/trigger/trigger.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#382 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#379 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, size/XS, lgtm

#383 Use the `controller.Impl` tracker
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/brokerstandalone/broker_test.go
  pkg/reconciler/brokerstandalone/controller.go
  pkg/reconciler/source/controller.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/reconciler/triggerstandalone/controller.go
  pkg/reconciler/triggerstandalone/trigger_test.go
Labels: cla: yes, approved, lgtm, size/M, kind/cleanup

#387 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#393 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M
