Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-03, with the labels that each got.

#237 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/clock.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/images/cmd.go
  vendor/knative.dev/reconciler-test/pkg/images/ko.go
  vendor/knative.dev/reconciler-test/pkg/knative/logging_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#238 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#243 fix codeowners to be single line
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#244 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/state/context.go
  vendor/knative.dev/reconciler-test/pkg/state/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/state/kvstore.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#249 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/environment/t.go
  vendor/knative.dev/reconciler-test/pkg/feature/collapse.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/t.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter.go
  vendor/knative.dev/reconciler-test/pkg/milestone/factory.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#248 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#250 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/t.go
  vendor/knative.dev/reconciler-test/pkg/feature/t.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#252 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#251 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/environment/t.go
  vendor/knative.dev/reconciler-test/pkg/environment/timings.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#255 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#258 test with less, seems we are getting throttled
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#256 vendor in conformance tests, add action for running them.
  .github/workflows/kind-conformance.yaml
  go.mod
  go.sum
  hack/tools.go
  test/conformance/conformance_test.go
  test/conformance/main_test.go
  test/conformance/testdata/with-operator/base.yaml
  test/conformance/testdata/with-operator/prereq.yaml
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/ingress.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/defaults.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/control_plane.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.go
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/eventing/test/rekt/resources/svc/service.go
  vendor/knative.dev/eventing/test/rekt/resources/svc/service.yaml
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
  vendor/knative.dev/eventing/test/test_images/event-flaker/main.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/timings.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/doc.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#257 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/ingress.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/defaults.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#259 update to new conformance
  go.mod
  go.sum
  test/conformance/conformance_test.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#261 grab latest conf tests
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/dropevents/receiver.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#262 enable manual push of conformance runs
  .github/workflows/kind-conformance.yaml
Labels: approved, cla: yes, lgtm, size/XS

#266 new conformance tests
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
