Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2021-02, with the labels that each got.

#220 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#222 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#221 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#224 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#225 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/pmezard/go-difflib/difflib/LICENSE
  third_party/VENDOR-LICENSE/github.com/stretchr/testify/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/NOTICE
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/step.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#226 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#229 Fail releasability if NO-GO
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#227 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#228 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#230 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#231 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#232 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#234 update deps for 0.21
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#233 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#235 e2e tests with eventing v0.21.0, drop v0.17.9
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS
