Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-06, with the labels that each got.

#796 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#797 Deprecate the use of RabbitMQCluster as a broker config. Document usage of new broker config
  samples/broker-trigger/quick-setup/250-broker-config.yaml
  samples/broker-trigger/quick-setup/300-broker.yaml
  samples/broker-trigger/quick-setup/README.md
  samples/broker-trigger/tracing/broker-config.yaml
  samples/broker-trigger/tracing/broker.yaml
  samples/broker-trigger/trigger-customizations/250-broker-config.yaml
  samples/broker-trigger/trigger-customizations/300-broker.yaml
  samples/broker-trigger/trigger-customizations/README.md
Labels: approved, lgtm, size/L, kind/documentation, kind/cleanup

#798 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#799 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#804 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#747 Create ADOPTERS.MD
  ADOPTERS.MD
Labels: approved, lgtm, size/S, kind/documentation

#807 added deprecation notice on release 1.5 branch source's readme
  docs/source/README.md
Labels: approved, lgtm, size/S

#808 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#809 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#811 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#815 Decreasing dispatcher and adapter resource cpu requests
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/ingress_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
Labels: approved, lgtm, size/S, kind/bug

#814 Fix DLQ flake
  pkg/rabbit/service.go
  pkg/rabbit/types.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, lgtm, size/M

#801 Source cluster reference
  config/source/201-clusterrole.yaml
  config/source/300-rabbitmqsource.yaml
  docs/source/README.md
  docs/source/source-example.yaml
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_lifecycle.go
  pkg/apis/sources/v1alpha1/rabbitmq_lifecycle_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/brokerconfig/service.go
  pkg/rabbit/queue.go
  pkg/rabbit/secret.go
  pkg/rabbit/secret_test.go
  pkg/rabbit/service.go
  pkg/rabbit/service_test.go
  pkg/rabbit/types.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/secret.go
  pkg/reconciler/broker/resources/secret_test.go
  pkg/reconciler/source/controller.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  pkg/reconciler/trigger/trigger.go
  samples/source/quick-setup/500-source.yaml
  samples/source/quick-setup/README.md
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.go
  test/e2e/config/rabbitmqvhost/credentials.yaml
  test/e2e/config/source/rabbitmq-source.yaml
  test/e2e/config/sourcevhost/rabbitmq-source-vhost.yaml
  test/e2e/config/vhostsourceproducer/vhost-producer.yaml
  test/e2e/rabbitmqcluster.go
Labels: approved, size/XXL, lgtm, kind/deprecation, kind/api-change

#821 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#828 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  third_party/pkg/client/clientset/versioned/clientset.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#824 Adds v1.5 perf results. Doc fixes
  test/performance/README.md
  test/performance/create-benchmarks.sh
  test/performance/results/release-v1.5/broker/constant-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.5/broker/constant-load/parallel-1-latency.png
  test/performance/results/release-v1.5/broker/constant-load/parallel-1-throughput.png
  test/performance/results/release-v1.5/broker/constant-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.5/broker/constant-load/parallel-100-latency.png
  test/performance/results/release-v1.5/broker/constant-load/parallel-100-throughput.png
  test/performance/results/release-v1.5/broker/increasing-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.5/broker/increasing-load/parallel-1-latency.png
  test/performance/results/release-v1.5/broker/increasing-load/parallel-1-throughput.png
  test/performance/results/release-v1.5/broker/increasing-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.5/broker/increasing-load/parallel-100-latency.png
  test/performance/results/release-v1.5/broker/increasing-load/parallel-100-throughput.png
  test/performance/results/release-v1.5/broker/multi-consumer/parallel-100-latency-throughput.png
  test/performance/results/release-v1.5/broker/multi-consumer/parallel-100-latency.png
  test/performance/results/release-v1.5/broker/multi-consumer/parallel-100-throughput.png
  test/performance/results/release-v1.5/source/constant-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.5/source/constant-load/parallel-1-latency.png
  test/performance/results/release-v1.5/source/constant-load/parallel-1-throughput.png
  test/performance/results/release-v1.5/source/constant-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.5/source/constant-load/parallel-100-latency.png
  test/performance/results/release-v1.5/source/constant-load/parallel-100-throughput.png
  test/performance/results/release-v1.5/source/increasing-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.5/source/increasing-load/parallel-1-latency.png
  test/performance/results/release-v1.5/source/increasing-load/parallel-1-throughput.png
  test/performance/results/release-v1.5/source/increasing-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.5/source/increasing-load/parallel-100-latency.png
  test/performance/results/release-v1.5/source/increasing-load/parallel-100-throughput.png
Labels: approved, lgtm, size/M, kind/documentation

#827 Override and escape component provided by controller.
  pkg/utils/envconfig.go
Labels: approved, size/XS, lgtm, kind/bug

#834 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#825 Make sure rabbitmq set up properly and test env allows reproducibility
  samples/broker-trigger/quick-setup/200-rabbitmq.yaml
  samples/broker-trigger/quick-setup/README.md
  samples/broker-trigger/tracing/400-cluster.yaml
  samples/broker-trigger/trigger-customizations/200-rabbitmq.yaml
  samples/broker-trigger/trigger-customizations/README.md
  samples/multiple-namespaces/200-rabbitmq-cluster.yaml
  samples/source/external-cluster/resources/rabbitmq-sample-deployment.yaml
  samples/source/quick-setup/200-rabbitmq.yaml
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.yaml
  test/e2e/config/rabbitmq/cluster.yaml
  test/e2e/config/rabbitmqvhost/clustervhost.yaml
Labels: approved, lgtm, size/L, kind/bug

#831 Source delivery fixes
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  samples/source/external-cluster/300-perf-test.yaml
  samples/source/quick-setup/300-perf-test.yaml
  samples/source/quick-setup/500-source.yaml
Labels: approved, lgtm, size/L, kind/bug

#836 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#837 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#838 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#841 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#845 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L
