Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-12, with the labels that each got.

#975 Added vhost capabilities to Brokers and Triggers
  cmd/dispatcher/main.go
  cmd/ingress/main.go
  config/broker/300-rabbitmqbrokerconfig.yaml
  pkg/apis/eventing/v1alpha1/rabbitmq_types.go
  pkg/brokerconfig/service.go
  pkg/rabbit/binding.go
  pkg/rabbit/binding_test.go
  pkg/rabbit/exchange.go
  pkg/rabbit/exchange_test.go
  pkg/rabbit/queue.go
  pkg/rabbit/queue_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/ingress_test.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  test/e2e/broker_test.go
  test/e2e/config/brokertriggervhost/broker.yaml
  test/e2e/config/brokertriggervhost/brokertrigger.go
  test/e2e/config/brokertriggervhost/trigger.yaml
  test/e2e/main_test.go
Labels: approved, size/XXL, lgtm, kind/enhancement

#1015 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_configmap.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1017 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1020 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1022 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1023 changing release 1.8 to support newest go autogenerated code changes
  pkg/adapter/adapter_test.go
  pkg/apis/duck/v1beta1/register_test.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  third_party/pkg/client/clientset/versioned/fake/register.go
  third_party/pkg/client/clientset/versioned/scheme/register.go
Labels: approved, size/XS, lgtm

#1021 Patch CVE-2022-41717
  go.mod
Labels: approved, size/XS, lgtm

#1024 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1025 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1027 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1028 Bumping to latest knative/eventing
  go.mod
  go.sum
  pkg/reconciler/broker/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1029 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1018 Removes using callbacks in webhooks. Relies on genericCRD interface instead to receive the defaulting and validating calls.
  cmd/webhook/broker/main.go
  pkg/apis/eventing/v1alpha1/broker_validation.go
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
  pkg/apis/eventing/v1alpha1/rabbitmq_types.go
  pkg/apis/eventing/v1alpha1/rabbitmq_validation.go
  pkg/apis/eventing/v1alpha1/trigger_validation.go
  pkg/apis/eventing/v1alpha1/trigger_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L, kind/cleanup

#1030 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1031 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L
