Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-09, with the labels that each got.

#913 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#914 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#916 Testing: e2e & conformance. Adds ability to specify custom images and secrets for rabbitmqclusters
  Makefile
  test/conformance/conformance_test.go
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.go
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.yaml
  test/e2e/config/rabbitmq/cluster.yaml
  test/e2e/config/rabbitmq/rabbitmq.go
  test/e2e/config/rabbitmqvhost/rabbitmqvhost.go
  test/e2e/rabbitmqcluster.go
Labels: approved, lgtm, size/L

#920 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#919 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#918 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go
  vendor/knative.dev/eventing/test/rekt/resources/pingsource/pingsource.go
  vendor/knative.dev/eventing/test/rekt/resources/pingsource/pingsource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/source/source.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/interface.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#915 Guest user available for e2e test in production RabbitMQ Clusters envs
  test/e2e/config/rabbitmqvhost/clustervhost.yaml
Labels: approved, size/XS, lgtm, kind/cleanup

#922 [release-1.6] Testing: e2e & conformance. Adds ability to specify custom images and secrets for rabbitmqclusters
  Makefile
  test/conformance/conformance_test.go
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.go
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.yaml
  test/e2e/config/rabbitmq/cluster.yaml
  test/e2e/config/rabbitmq/rabbitmq.go
  test/e2e/config/rabbitmqvhost/rabbitmqvhost.go
  test/e2e/rabbitmqcluster.go
Labels: approved, lgtm, size/L

#917 added convert to rabbitmq method to protocol binding + tests
  cmd/ingress/main.go
  pkg/rabbit/message.go
  pkg/rabbit/message_test.go
Labels: approved, lgtm, size/L, kind/cleanup

#925 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/features/broker/topology.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#926 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#927 Adds support for eventing-rabbitmq->RMQ SSL communication with self-signed certs
  pkg/rabbit/service.go
  pkg/rabbit/service_test.go
  pkg/rabbit/types.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/ingress_test.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, lgtm, size/XL, kind/enhancement

#930 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#931 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
