Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-05, with the labels that each got.

#734 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#736 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#738 Updates resource limits for source controller
  config/source/500-controller.yaml
Labels: approved, size/XS, lgtm, kind/enhancement

#737 Adds troubleshooting steps
  docs/broker/README.md
  docs/source/README.md
Labels: approved, lgtm, size/M, kind/documentation

#741 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#742 Run go mod tidy
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#743 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#744 switches back to DeepDerivative as deployments were aggressively updated
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, lgtm, size/S, kind/bug

#745 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#750 Fixed Receive Adapter and Dispatcher BackoffDelay period parsing
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
Labels: approved, lgtm, size/S, kind/bug

#753 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#754 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#755 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#756 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#757 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#761 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#762 Removes list of retryable status codes from docs. Link to offical spec still present
  docs/broker/README.md
Labels: approved, size/XS, lgtm, kind/documentation

#766 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#768 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#751 Broker ingress and Dispatcher now uses the protocol binding instead of json to process events
  .codecov.yaml
  .golangci.yaml
  cmd/ingress/main.go
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/adapter/message_test.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/rabbit/message.go
  pkg/rabbit/message_test.go
  test/e2e/cmd/rabbitproducer/main.go
  test/performance/README.md
  test/performance/results/release-v1.3/source/increasing-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.3/source/increasing-load/parallel-1-latency.png
  test/performance/results/release-v1.3/source/increasing-load/parallel-1-throughput.png
  test/performance/results/release-v1.4/source/constant-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.4/source/constant-load/parallel-1-latency.png
  test/performance/results/release-v1.4/source/constant-load/parallel-1-throughput.png
  test/performance/results/release-v1.4/source/constant-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.4/source/constant-load/parallel-100-latency.png
  test/performance/results/release-v1.4/source/constant-load/parallel-100-throughput.png
  test/performance/results/release-v1.4/source/increasing-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.4/source/increasing-load/parallel-1-latency.png
  test/performance/results/release-v1.4/source/increasing-load/parallel-1-throughput.png
  test/performance/results/release-v1.4/source/increasing-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.4/source/increasing-load/parallel-100-latency.png
  test/performance/results/release-v1.4/source/increasing-load/parallel-100-throughput.png
Labels: approved, size/XXL, lgtm, kind/enhancement, kind/performance

#770 fixing rabbitmq's cluster operator version
  Makefile
  test/performance/README.md
Labels: approved, size/XS, lgtm

#776 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#775 Added production like rabbitmq cluster yaml definition to performance test
  test/performance/broker-setup/100-broker-perf-setup.yaml
  test/performance/source-setup/100-rabbitmq-setup.yaml
Labels: approved, lgtm, size/L, kind/performance

#771 Deployments resources
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  Makefile
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/ingress_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  test/e2e/kind.yaml
Labels: approved, lgtm, size/L, kind/enhancement

#774 Adds RabbitmqBrokerConfig type to be used for configuring a Broker/Trigger
  Makefile
  cmd/webhook/broker/main.go
  config/broker/300-rabbitmqbrokerconfig.yaml
  hack/update-codegen.sh
  pkg/apis/eventing/v1alpha1/broker_validation.go
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
  pkg/apis/eventing/v1alpha1/doc.go
  pkg/apis/eventing/v1alpha1/rabbitmq_defaults.go
  pkg/apis/eventing/v1alpha1/rabbitmq_types.go
  pkg/apis/eventing/v1alpha1/rabbitmq_types_test.go
  pkg/apis/eventing/v1alpha1/rabbitmq_validation.go
  pkg/apis/eventing/v1alpha1/rabbitmq_validation_test.go
  pkg/apis/eventing/v1alpha1/register.go
  pkg/apis/eventing/v1alpha1/trigger_validation.go
  pkg/apis/eventing/v1alpha1/trigger_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_rabbitmqbrokerconfig.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/rabbitmqbrokerconfig.go
  pkg/client/informers/externalversions/eventing/interface.go
  pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  pkg/client/informers/externalversions/eventing/v1alpha1/rabbitmqbrokerconfig.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/eventing/v1alpha1/rabbitmqbrokerconfig/fake/fake.go
  pkg/client/injection/informers/eventing/v1alpha1/rabbitmqbrokerconfig/filtered/fake/fake.go
  pkg/client/injection/informers/eventing/v1alpha1/rabbitmqbrokerconfig/filtered/rabbitmqbrokerconfig.go
  pkg/client/injection/informers/eventing/v1alpha1/rabbitmqbrokerconfig/rabbitmqbrokerconfig.go
  pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  pkg/client/listers/eventing/v1alpha1/rabbitmqbrokerconfig.go
Labels: approved, lgtm, size/XL, kind/enhancement

#777 fixed source docs
  docs/source/README.md
  docs/source/rabbitmq-knative-source.png
Labels: approved, lgtm, size/S, kind/documentation

#779 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#780 Broker / Trigger can use RabbitmqBrokerConfig or a RabbitMQCluster as its config
  config/broker/200-rabbitmq-broker-clusterrole.yaml
  pkg/apis/eventing/v1alpha1/broker_validation.go
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
  pkg/brokerconfig/service.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_config.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/testing/factory.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, size/XXL, lgtm, kind/enhancement

#784 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/source/config_watcher.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#785 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm

#788 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#778 fixed cleanup logic to rabbit connections
  cmd/ingress/main.go
  pkg/rabbit/setup.go
  pkg/rabbit/setup_test.go
Labels: approved, lgtm, size/M, kind/bug

#786 Improved RabbitMQ Source documentation
  docs/broker/README.md
  docs/source/README.md
  docs/source/source-example.yaml
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  samples/broker-trigger/quick-setup/100-namespace.yaml
  samples/broker-trigger/quick-setup/200-rabbitmq.yaml
  samples/broker-trigger/quick-setup/300-broker.yaml
  samples/broker-trigger/quick-setup/400-sink.yaml
  samples/broker-trigger/quick-setup/500-ping-sources.yaml
  samples/broker-trigger/quick-setup/600-trigger.yaml
  samples/broker-trigger/quick-setup/700-failer.yaml
  samples/broker-trigger/quick-setup/README.md
  samples/broker-trigger/tracing/100-ns.yaml
  samples/broker-trigger/tracing/README.md
  samples/broker-trigger/tracing/broker.yaml
  samples/broker-trigger/tracing/cluster.yaml
  samples/broker-trigger/tracing/sink.yaml
  samples/broker-trigger/tracing/source.yaml
  samples/broker-trigger/tracing/trigger.yaml
  samples/broker-trigger/trigger-customizations/100-namespace.yaml
  samples/broker-trigger/trigger-customizations/200-rabbitmq.yaml
  samples/broker-trigger/trigger-customizations/300-broker.yaml
  samples/broker-trigger/trigger-customizations/400-trigger.yaml
  samples/broker-trigger/trigger-customizations/500-sink.yaml
  samples/broker-trigger/trigger-customizations/600-event-sender.yaml
  samples/broker-trigger/trigger-customizations/README.md
  samples/broker-trigger/trigger-customizations/event-display/main.go
  samples/broker-trigger/trigger-customizations/event-sender/main.go
  samples/multiple-namespaces/400-rabbitmq_cluster.yaml
  samples/source/external-cluster/100-namespace.yaml
  samples/source/external-cluster/200-perf-test.yaml
  samples/source/external-cluster/300-sink.yaml
  samples/source/external-cluster/400-source.yaml
  samples/source/external-cluster/README.md
  samples/source/external-cluster/resources/rabbitmq.yml
  samples/source/quick-setup/100-namespace.yaml
  samples/source/quick-setup/200-rabbitmq.yaml
  samples/source/quick-setup/300-perf-test.yaml
  samples/source/quick-setup/400-sink.yaml
  samples/source/quick-setup/500-source.yaml
  samples/source/quick-setup/README.md
  test/performance/README.md
Labels: approved, lgtm, size/XL, kind/documentation, kind/cleanup

#790 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#793 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm
