Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-07, with the labels that each got.

#848 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/conditions/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/source/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/source/source.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#852 Removes remnants of the old producer (messageCount)
  Makefile
  test/e2e/config/brokersecret/brokersecret.go
  test/e2e/config/brokertrigger/brokertrigger.go
  test/e2e/direct_test.go
  test/e2e/dispatcher_test.go
  test/e2e/main_test.go
  test/e2e/recorder.go
Labels: approved, lgtm, size/M, kind/cleanup

#854 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#856 Sets prefetch to a static 100. Update docs
  cmd/dispatcher/main.go
  docs/broker/README.md
Labels: approved, lgtm, size/S, kind/performance, kind/removal

#857 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#863 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#864 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#865 Uploads release-v1.6 performance results
  test/performance/results/release-v1.6/broker/constant-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.6/broker/constant-load/parallel-1-latency.png
  test/performance/results/release-v1.6/broker/constant-load/parallel-1-throughput.png
  test/performance/results/release-v1.6/broker/constant-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.6/broker/constant-load/parallel-100-latency.png
  test/performance/results/release-v1.6/broker/constant-load/parallel-100-throughput.png
  test/performance/results/release-v1.6/broker/increasing-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.6/broker/increasing-load/parallel-1-latency.png
  test/performance/results/release-v1.6/broker/increasing-load/parallel-1-throughput.png
  test/performance/results/release-v1.6/broker/increasing-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.6/broker/increasing-load/parallel-100-latency.png
  test/performance/results/release-v1.6/broker/increasing-load/parallel-100-throughput.png
  test/performance/results/release-v1.6/broker/multi-consumer/parallel-100-latency-throughput.png
  test/performance/results/release-v1.6/broker/multi-consumer/parallel-100-latency.png
  test/performance/results/release-v1.6/broker/multi-consumer/parallel-100-throughput.png
  test/performance/results/release-v1.6/source/constant-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.6/source/constant-load/parallel-1-latency.png
  test/performance/results/release-v1.6/source/constant-load/parallel-1-throughput.png
  test/performance/results/release-v1.6/source/constant-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.6/source/constant-load/parallel-100-latency.png
  test/performance/results/release-v1.6/source/constant-load/parallel-100-throughput.png
  test/performance/results/release-v1.6/source/increasing-load/parallel-1-latency-throughput.png
  test/performance/results/release-v1.6/source/increasing-load/parallel-1-latency.png
  test/performance/results/release-v1.6/source/increasing-load/parallel-1-throughput.png
  test/performance/results/release-v1.6/source/increasing-load/parallel-100-latency-throughput.png
  test/performance/results/release-v1.6/source/increasing-load/parallel-100-latency.png
  test/performance/results/release-v1.6/source/increasing-load/parallel-100-throughput.png
Labels: approved, size/XS, lgtm, kind/documentation

#868 Attempts to remove any leftover DLQ resources that are no longer needed
  pkg/rabbit/service.go
  pkg/rabbit/types.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, lgtm, size/L, kind/bug

#870 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#873 Update README.md
  README.md
Labels: approved, size/XS, lgtm

#871 bump to go 1.18
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/XL, kind/enhancement

#875 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#876 Consistent naming
  ADOPTERS.MD
  README.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/broker/README.md
  docs/source/README.md
  hack/README.md
  samples/external-cluster/README.md
  samples/multiple-namespaces/README.md
  samples/quick-setup/README.md
  samples/tracing/README.md
  samples/trigger-customizations/README.md
  test/performance/README.md
Labels: approved, lgtm, size/M, kind/documentation
