Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-10, with the labels that each got.

#929 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#932 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#935 Update deps + Bump cloudevents/sdk-go/sql to 52b12276cc4a
  go.mod
  go.sum
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_config_set.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserialization_options.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserializer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/error_strategy.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/lexer_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/ll1_analyzer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/recognizer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/semantic_context.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/tree.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils_set.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/README.md
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParser.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParserLexer.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_base_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_lexer.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_parser.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_visitor.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#933 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#936 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#938 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#940 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#941 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, skip-review

#943 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#944 Update k8s versions for GH actions. Updates knative versions for e2e tests.
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  Makefile
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/reactor.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#942 Adds e2e tests for Source and Broker which uses RabbitMQ cluster instances with TLS (self-signed)
  test/e2e/cmd/rabbitproducer/main.go
  test/e2e/config/certsecret/certsecret.go
  test/e2e/config/certsecret/secret.yaml
  test/e2e/config/rabbitmq/cluster.yaml
  test/e2e/config/rabbitmq/rabbitmq.go
  test/e2e/config/sourceproducer/producer.yaml
  test/e2e/config/sourceproducer/sourceproducer.go
  test/e2e/config/vhostsourceproducer/vhost-producer.yaml
  test/e2e/main_test.go
  test/e2e/rabbitmqcluster.go
  test/e2e/selfsignedcerts.go
  test/e2e/source_test.go
Labels: approved, lgtm, size/L

#934 Adds docs for self-signed certificate support
  docs/README.md
  docs/self-signed-certs/README.md
Labels: approved, lgtm, size/M, kind/documentation

#946 Codecov Fix
  .codecov.yaml
Labels: approved, lgtm, size/S, kind/cleanup

#947 Resource request and limits can be set for Broker, Trigger and Source
  pkg/apis/eventing/v1alpha1/broker_validation.go
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
  pkg/apis/eventing/v1alpha1/trigger_validation.go
  pkg/apis/eventing/v1alpha1/trigger_validation_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/broker_test_helper.go
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/utils/resource_requirements.go
  pkg/utils/resource_requirements_test.go
Labels: approved, lgtm, size/XL, kind/enhancement

#949 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#952 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#948 Docs for resource requirements
  docs/README.md
  docs/pod-resources/README.md
Labels: approved, lgtm, size/M, kind/documentation

#951 Adds an e2e run to test with the latest of eventing
  .github/workflows/kind-e2e.yaml
  Makefile
Labels: approved, lgtm, size/S

#953 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#954 Fix: Specify `securityContext`.
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/ingress_test.go
Labels: approved, lgtm, size/M, kind/bug

#955 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#956 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#958 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#959 Fix Source log leak when predeclared resources are not created
  pkg/rabbit/types.go
  pkg/reconciler/source/rabbitmqsource.go
Labels: approved, lgtm, size/S, kind/bug

#964 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#965 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#966 Fix: Capitalize ALL when dropping capabilities.
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/ingress_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
Labels: approved, lgtm, size/S, kind/bug

#967 Fix: Add `securityContext` to Trigger dispatcher.
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
Labels: approved, lgtm, size/S, kind/bug

#968 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#971 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#974 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#976 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#977 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#980 Revert "added queue and exchange existance verification to source controller to avoid not existing errors (#959)"
  pkg/rabbit/types.go
  pkg/reconciler/source/rabbitmqsource.go
Labels: approved, lgtm, size/S, kind/bug
