Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-03, with the labels that each got.

#617 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm

#633 increase conformance test suite timeout to 1h
  Makefile
Labels: approved, size/XS, lgtm

#621 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#639 manual cherry-pick for conf tests timeouts and parallelism
  Makefile
Labels: approved, size/XS, lgtm, kind/cleanup

#640 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#643 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#620 Rabbitmqsource schema
  Makefile
  config/source/300-rabbitmqsource.yaml
  pkg/apis/sources/v1alpha1/doc.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  samples/source/README.md
  source/README.md
  source/source-example.yaml
  test/e2e/config/source/rabbitmq-source.yaml
  test/e2e/config/sourcevhost/rabbitmq-source-vhost.yaml
Labels: approved, lgtm, size/XL, kind/cleanup

#651 Fix source samples
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  samples/source/500-source.yaml
  source/source-example.yaml
Labels: approved, lgtm, size/L, kind/cleanup

#644 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#653 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#656 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/fake/fake_broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/fake/fake_trigger.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/fake/fake_parallel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/fake/fake_sequence.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/flows_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_channel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_subscription.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/messaging_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/sources_client.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#655 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, size/XS, lgtm

#652 Small refactors: remove unused context from NewExchange() and NewQueue()
  pkg/rabbit/service.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/resources/queue_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#660 Increase memory request/limit to 1Gi
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.yaml
Labels: approved, size/XS, lgtm, kind/cleanup

#661 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#600 Minor test/README.md edits
  test/README.md
Labels: approved, lgtm, size/S, kind/documentation

#614 Source backoff strategy on failed events
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/brokerstandalone/broker_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  pkg/reconciler/triggerstandalone/trigger_test.go
  source/source-example.yaml
Labels: approved, lgtm, size/XL, kind/performance

#608 [Docs] Adds trigger performance examples
  broker/README.md
  samples/trigger-customizations/100-namespace.yaml
  samples/trigger-customizations/200-rabbitmq.yaml
  samples/trigger-customizations/300-broker.yaml
  samples/trigger-customizations/400-trigger.yaml
  samples/trigger-customizations/500-sink.yaml
  samples/trigger-customizations/600-event-sender.yaml
  samples/trigger-customizations/README.md
  samples/trigger-customizations/event-display/main.go
  samples/trigger-customizations/event-sender/main.go
Labels: approved, lgtm, size/XL, kind/documentation

#663 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/XL

#665 Create messaging topology objects for rabbitmqsource
  Makefile
  config/source/201-clusterrole.yaml
  config/source/300-rabbitmqsource.yaml
  go.mod
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/rabbit/service.go
  pkg/rabbitmqnaming/naming.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_config.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/source/controller.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/trigger/resources/binding.go
  pkg/reconciler/trigger/resources/binding_test.go
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  test/e2e/config/source/rabbitmq-source.yaml
  test/e2e/config/sourcevhost/rabbitmq-source-vhost.yaml
  test/e2e/rabbitmqcluster.go
Labels: approved, size/XXL, lgtm, kind/bug, kind/api-change

#667 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#642 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#669 Update rabbitmqsource crd for added delivery configurations
  config/source/300-rabbitmqsource.yaml
Labels: approved, lgtm, size/S

#670 Rename rmqsource exchangeConfig TypeOf to Type
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/reconciler/broker/resources/exchange.go
  pkg/reconciler/broker/resources/exchange_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
Labels: approved, lgtm, size/S, kind/cleanup

#675 Ignore test/ for codecov
  .codecov.yaml
Labels: approved, size/XS, lgtm, kind/cleanup

#673 Move NewPolicy() NewExchange() NewBinding() NewQueue() to pkg/rabbit
  pkg/rabbit/binding.go
  pkg/rabbit/binding_test.go
  pkg/rabbit/exchange.go
  pkg/rabbit/exchange_test.go
  pkg/rabbit/queue.go
  pkg/rabbit/queue_test.go
  pkg/rabbit/service.go
  pkg/rabbit/types.go
  pkg/rabbitmqnaming/naming_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_config.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/secret.go
  pkg/reconciler/broker/resources/secret_test.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, lgtm, size/L, kind/cleanup

#672 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L
