Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-04, with the labels that each got.

#676 Better naming for prefetchCoun env var
  broker/README.md
  cmd/dispatcher/main.go
  config/source/300-rabbitmqsource.yaml
  pkg/adapter/adapter.go
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_defaults.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/reconciler/trigger/trigger_test.go
  samples/broker-trigger/600-trigger.yaml
  samples/broker-trigger/README.md
  samples/source/500-source.yaml
  samples/trigger-customizations/400-trigger.yaml
  samples/trigger-customizations/README.md
  source/README.md
  test/e2e/config/brokertrigger/brokertrigger.go
  test/e2e/config/brokertrigger/trigger.yaml
  test/e2e/config/source/rabbitmq-source.yaml
  test/e2e/dispatcher_test.go
  test/performance/broker-rmq/100-broker-perf-setup.yaml
Labels: approved, lgtm, size/L, kind/enhancement

#679 Name queue&exchange name required for rabbitmqsource
  config/source/300-rabbitmqsource.yaml
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
Labels: approved, lgtm, size/M, kind/enhancement

#678 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#680 Add connectionSecret to rabbitmqsource examples
  samples/source/500-source.yaml
  samples/source/README.md
  source/source-example.yaml
Labels: approved, lgtm, size/M, kind/documentation

#682 Merges with up-to-date main before running tests
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#684 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#688 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/L

#686 Remove internal exchange and exclusive queue config from rabbitmqsource
  config/source/300-rabbitmqsource.yaml
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/rabbit/exchange_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  samples/source/500-source.yaml
  samples/source/README.md
  source/README.md
  source/source-example.yaml
Labels: approved, lgtm, size/L, kind/cleanup

#689 Rename rmqsource spec.brokers to broker
  config/source/300-rabbitmqsource.yaml
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  samples/source/500-source.yaml
  samples/source/README.md
  test/e2e/config/source/rabbitmq-source.yaml
  test/e2e/config/sourcevhost/rabbitmq-source-vhost.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#691 Fix the golangci linter
  pkg/apis/sources/v1alpha1/rabbitmq_validation.go
Labels: approved, size/XS, lgtm, kind/cleanup

#685 Refactoring docs into `docs/` dir
  README.md
  docs/README.md
  docs/broker.md
  docs/operator-based.md
  docs/rabbitmq-knative-broker.png
  docs/source-example.yaml
  docs/source.md
  docs/standalone.md
  docs/test.md
  samples/source/README.md
Labels: approved, lgtm, size/M, kind/documentation

#681 Cleanup unnecessary resource creation when DeliverySpec is not defined
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, lgtm, size/L, kind/cleanup

#668 Organizing Broker's performance test benchmars
  README.md
  test/performance/broker-rmq/100-broker-perf-setup.yaml
  test/performance/broker-rmq/README.md
  test/performance/broker-rmq/constant-load/300-broker-perf-consumer-job.yaml
  test/performance/broker-rmq/constant-load/prefetch-1-latency-throughput.png
  test/performance/broker-rmq/constant-load/prefetch-1-latency.png
  test/performance/broker-rmq/constant-load/prefetch-1-throughput.png
  test/performance/broker-rmq/constant-load/prefetch-100-latency-throughput.png
  test/performance/broker-rmq/constant-load/prefetch-100-latency.png
  test/performance/broker-rmq/constant-load/prefetch-100-throughput.png
  test/performance/broker-rmq/increasing-load/200-broker-perf-consumer-job.yaml
  test/performance/broker-rmq/increasing-load/prefetch-1-latency-throughput.png
  test/performance/broker-rmq/increasing-load/prefetch-1-latency.png
  test/performance/broker-rmq/increasing-load/prefetch-1-throughput.png
  test/performance/broker-rmq/increasing-load/prefetch-100-latency-throughput.png
  test/performance/broker-rmq/increasing-load/prefetch-100-latency.png
  test/performance/broker-rmq/increasing-load/prefetch-100-throughput.png
  test/performance/broker-rmq/latency-throughput.png
  test/performance/broker-rmq/latency.png
  test/performance/broker-rmq/throughput.png
Labels: approved, lgtm, size/L, kind/performance

#693 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm

#690 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#692 Remove spec.topic in RabbitmqSource
  config/source/300-rabbitmqsource.yaml
  docs/source-example.yaml
  docs/source.md
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/adapter/message.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
  pkg/apis/sources/v1alpha1/rabbitmq_validation_test.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
  samples/source/500-source.yaml
  samples/source/README.md
  test/e2e/config/source/rabbitmq-source.yaml
  test/e2e/config/sourcevhost/rabbitmq-source-vhost.yaml
Labels: approved, lgtm, size/M, kind/enhancement

#694 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#695 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/trigger_sink_resolution.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#696 Make rabbitmqsource spec.sink a required property
  config/source/300-rabbitmqsource.yaml
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
Labels: approved, size/XS, lgtm, kind/enhancement

#698 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#701 Set default for rmqsource in CRD instead of webhook
  config/source/300-rabbitmqsource.yaml
  pkg/apis/sources/v1alpha1/rabbitmq_defaults.go
  pkg/apis/sources/v1alpha1/rabbitmq_types.go
Labels: approved, lgtm, size/S, kind/enhancement

#702 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#704 Bump min k8s version + dependency updates
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  Makefile
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#705 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#700 Cleanup code
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/dispatcher/dispatcher_test.go
  pkg/rabbit/binding.go
  pkg/rabbit/exchange.go
  pkg/rabbit/exchange_test.go
  pkg/rabbit/label.go
  pkg/rabbit/label_test.go
  pkg/rabbit/queue.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/broker_test_helper.go
  pkg/reconciler/source/rabbitmqsource.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/triggerstandalone/resources/binding.go
  pkg/reconciler/triggerstandalone/resources/queue.go
  pkg/reconciler/triggerstandalone/trigger.go
Labels: approved, lgtm, size/L, kind/cleanup

#707 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#699 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#648 Broker's Ingress RabbitMQ Channel and Connection recovery
  cmd/dispatcher/main.go
  cmd/ingress/main.go
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/amqp/amqp.go
  pkg/dispatcher/dispatcher_test.go
  pkg/rabbit/service.go
  pkg/rabbit/service_test.go
  pkg/rabbit/setup.go
  pkg/rabbit/setup_test.go
Labels: approved, lgtm, size/L, kind/enhancement

#711 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#712 Update docs to remove refs to standalone
  docs/broker.md
  docs/operator-based.md
  docs/standalone.md
  docs/test.md
Labels: approved, lgtm, size/L, kind/documentation

#713 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, size/XS, lgtm

#715 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#717 fix broken link
  docs/source.md
Labels: approved, size/XS, lgtm, kind/documentation

#716 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_configmap.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_environment.go
  vendor/knative.dev/eventing/pkg/adapter/v2/context.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/util/crstatusevent/eventsstatus.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#718 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#722 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#724 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#721 Perf test organization
  docs/CONTRIBUTING.md
  docs/DEVELOPMENT.md
  docs/README.md
  docs/broker/README.md
  docs/broker/rabbitmq-knative-broker.png
  docs/source/README.md
  docs/source/rabbitmq-knative-source.png
  docs/source/source-example.yaml
  source/PROJECT
  test/README.md
  test/performance/README.md
  test/performance/broker-rmq/constant-load/prefetch-1-latency-throughput.png
  test/performance/broker-rmq/constant-load/prefetch-1-latency.png
  test/performance/broker-rmq/constant-load/prefetch-1-throughput.png
  test/performance/broker-rmq/constant-load/prefetch-100-latency-throughput.png
  test/performance/broker-rmq/constant-load/prefetch-100-latency.png
  test/performance/broker-rmq/constant-load/prefetch-100-throughput.png
  test/performance/broker-rmq/increasing-load/prefetch-1-latency-throughput.png
  test/performance/broker-rmq/increasing-load/prefetch-1-latency.png
  test/performance/broker-rmq/increasing-load/prefetch-1-throughput.png
  test/performance/broker-rmq/increasing-load/prefetch-100-latency-throughput.png
  test/performance/broker-rmq/increasing-load/prefetch-100-latency.png
  test/performance/broker-rmq/increasing-load/prefetch-100-throughput.png
  test/performance/broker-setup/100-broker-perf-setup.yaml
  test/performance/broker-setup/200-broker-increasing-load-setup.yaml
  test/performance/broker-setup/300-broker-constant-load-setup.yaml
  test/performance/latency-throughput.plg
  test/performance/latency.plg
  test/performance/results/release-v1.3/broker/constant-load/prefetch-1-latency-throughput.png
  test/performance/results/release-v1.3/broker/constant-load/prefetch-1-latency.png
  test/performance/results/release-v1.3/broker/constant-load/prefetch-1-throughput.png
  test/performance/results/release-v1.3/broker/constant-load/prefetch-100-latency-throughput.png
  test/performance/results/release-v1.3/broker/constant-load/prefetch-100-latency.png
  test/performance/results/release-v1.3/broker/constant-load/prefetch-100-throughput.png
  test/performance/results/release-v1.3/broker/increasing-load/prefetch-1-latency-throughput.png
  test/performance/results/release-v1.3/broker/increasing-load/prefetch-1-latency.png
  test/performance/results/release-v1.3/broker/increasing-load/prefetch-1-throughput.png
  test/performance/results/release-v1.3/broker/increasing-load/prefetch-100-latency-throughput.png
  test/performance/results/release-v1.3/broker/increasing-load/prefetch-100-latency.png
  test/performance/results/release-v1.3/broker/increasing-load/prefetch-100-throughput.png
  test/performance/throughput.plg
Labels: approved, lgtm, size/L, kind/enhancement

#723 Broker and Trigger use delivery spec for dead letter messaging
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, lgtm, size/L, kind/bug

#725 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#687 Adds timeout to dispatcher.
  cmd/dispatcher/main.go
  cmd/webhook/broker/main.go
  go.mod
  go.sum
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/utils/http.go
  pkg/utils/http_test.go
  samples/trigger-customizations/event-display/main.go
Labels: approved, lgtm, size/L, kind/enhancement

#720 Adds troubleshooting, delivery spec customizations to broker/trigger docs
  docs/broker/README.md
Labels: approved, lgtm, size/M

#727 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#728 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#729 [e2e] Adds teardown step to clean up resources
  test/e2e/direct_test.go
  test/e2e/dispatcher_test.go
  test/e2e/dlq_test.go
  test/e2e/receive_adapter_test.go
  test/e2e/smoke_test_broker.go
  test/e2e/smoke_test_broker_trigger.go
  test/e2e/source_test.go
  test/e2e/sourcevhost_test.go
Labels: approved, lgtm, size/S, kind/cleanup

#730 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#726 Adds upgrade and uninstall instructions to broker and source.
  docs/broker/README.md
  docs/source/README.md
Labels: approved, lgtm, size/M

#731 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M
