Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-11, with the labels that each got.

#981 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#979 Update docs
  docs/self-signed-certs/README.md
Labels: approved, size/XS, lgtm

#987 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#989 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#988 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/security/security.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/knative.dev/reconciler-test/pkg/manifest/yaml.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#994 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#997 fixed kind version cause the other sha was failing for local development
  Makefile
Labels: approved, size/XS, lgtm

#998 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, skip-review

#996 RabbitmqCluster Connection Secret improvements
  pkg/rabbit/service.go
  pkg/rabbit/service_test.go
  samples/external-cluster/200-secret.yaml
  samples/external-cluster/README.md
  samples/rabbitmq-mtls/README.md
  test/e2e/config/broker/broker.yaml
  test/e2e/config/brokersecret/broker-config.yaml
  test/e2e/config/brokersecret/broker.yaml
  test/e2e/config/brokersecret/trigger.yaml
  test/e2e/config/brokertrigger/broker.yaml
  test/e2e/config/brokertrigger/trigger.yaml
  test/e2e/config/smoke/broker/smoke.yaml
  test/e2e/config/smoke/brokertrigger/smoke.yaml
  test/e2e/main_test.go
  test/e2e/rabbitmqcluster.go
  test/e2e/selfsignedcerts.go
  test/e2e/source_test.go
Labels: approved, lgtm, size/L, kind/enhancement

#995 ClusterRef Default Namespace fix
  cmd/webhook/broker/main.go
  config/broker/500-webhook-defaulting.yaml
  pkg/apis/eventing/v1alpha1/rabbitmq_defaults.go
  pkg/apis/eventing/v1alpha1/rabbitmq_defaults_test.go
  pkg/apis/sources/v1alpha1/rabbitmq_defaults.go
  pkg/apis/sources/v1alpha1/rabbitmq_defaults_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, lgtm, size/L, kind/bug

#1000 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, size/L

#1003 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1006 removed stringptr usage from dispatcher tests
  pkg/reconciler/trigger/resources/dispatcher_test.go
Labels: approved, size/XS, lgtm

#1005 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1008 Adds disk_free_limit to test clusters to prevent flakes with unconfirmed messages
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.yaml
  test/e2e/config/rabbitmq/cluster.yaml
  test/e2e/config/rabbitmqvhost/clustervhost.yaml
Labels: approved, size/XS, lgtm

#1007 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, size/L

#1009 Temporarily skip the 2 flakey e2e tests
  test/e2e/main_test.go
Labels: approved, size/XS, lgtm

#1002 Protocol binding refactor
  cmd/dispatcher/main.go
  cmd/ingress/main.go
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/rabbit/connections_handler.go
  pkg/rabbit/connections_handler_test.go
  pkg/rabbit/queue.go
  pkg/rabbit/rabbit_mocks.go
  pkg/rabbit/service.go
  pkg/rabbit/setup.go
  pkg/rabbit/setup_test.go
Labels: approved, size/XXL, lgtm, kind/enhancement

#1012 re-enable skipped e2e tests
  test/e2e/config/brokersecret/broker.yaml
  test/e2e/main_test.go
Labels: approved, size/XS, lgtm

#1013 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L
