Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-01, with the labels that each got.

#560 Configuring messages sent into the RabbitMQ CRDs to be Persistent
  cmd/ingress/main.go
Labels: approved, size/XS, lgtm, kind/bug

#556 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#557 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, size/XS, lgtm

#559 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#568 Add publisher confirms to ingress
  cmd/ingress/main.go
  go.mod
  go.sum
  vendor/github.com/rabbitmq/amqp091-go/.gitignore
  vendor/github.com/rabbitmq/amqp091-go/allocator.go
  vendor/github.com/rabbitmq/amqp091-go/auth.go
  vendor/github.com/rabbitmq/amqp091-go/channel.go
  vendor/github.com/rabbitmq/amqp091-go/confirms.go
  vendor/github.com/rabbitmq/amqp091-go/connection.go
  vendor/github.com/rabbitmq/amqp091-go/consumers.go
  vendor/github.com/rabbitmq/amqp091-go/delivery.go
  vendor/github.com/rabbitmq/amqp091-go/doc.go
  vendor/github.com/rabbitmq/amqp091-go/fuzz.go
  vendor/github.com/rabbitmq/amqp091-go/read.go
  vendor/github.com/rabbitmq/amqp091-go/return.go
  vendor/github.com/rabbitmq/amqp091-go/spec091.go
  vendor/github.com/rabbitmq/amqp091-go/types.go
  vendor/github.com/rabbitmq/amqp091-go/uri.go
  vendor/github.com/rabbitmq/amqp091-go/write.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, kind/enhancement

#569 Fix test targets to actually fail
  Makefile
Labels: approved, lgtm, size/S, kind/bug

#572 Small things
  cmd/failer/main.go
  pkg/apis/duck/v1beta1/rabbit.go
  pkg/apis/sources/register.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/broker_test_helper.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/brokerstandalone/broker_test.go
  pkg/reconciler/brokerstandalone/broker_test_helper.go
  pkg/reconciler/brokerstandalone/resources/ingress.go
  pkg/reconciler/testing/factory.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/reconciler/triggerstandalone/trigger_test.go
  test/e2e/cmd/producer/main.go
  test/e2e/cmd/rabbitproducer/main.go
Labels: approved, lgtm, ok-to-test, size/M, kind/cleanup

#580 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#579 Fixing workflow errors
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  Makefile
Labels: approved, lgtm, size/S

#533 Use policies for broker/trigger queue creation
  config/broker/200-rabbitmq-broker-clusterrole.yaml
  pkg/rabbit/service.go
  pkg/reconciler/trigger/resources/queue.go
  pkg/reconciler/trigger/resources/queue_test.go
  pkg/reconciler/trigger/trigger_test.go
Labels: cla: yes, approved, lgtm, size/L, kind/bug

#567 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/delivery.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/level.go
  vendor/knative.dev/reconciler-test/pkg/feature/states.go
  vendor/knative.dev/reconciler-test/pkg/feature/timing.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_log.go
  vendor/knative.dev/reconciler-test/pkg/state/kvstore.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#570 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, size/XS, lgtm

#571 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#589 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm
