Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2022-02, with the labels that each got.

#596 Increases worker node count to 2 for e2e/conformance tests
  test/e2e/kind.yaml
Labels: approved, size/XS, lgtm, kind/performance

#599 Put together short testing guide, .env -> (direnv friendly).envrc
  .github/workflows/kind-conformance-standalone.yaml
  .github/workflows/kind-conformance.yaml
  Makefile
  README.md
  test/README.md
Labels: approved, lgtm, size/L, kind/documentation, kind/cleanup

#594 Cloud event client creation uses kncloudevents retry conditions
  pkg/dispatcher/dispatcher.go
Labels: approved, size/XS, lgtm, kind/cleanup

#590 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#604 Fix make reset
  Makefile
Labels: approved, size/XS, lgtm, kind/bug

#598 Fixing conformance and e2e workflows tests
  Makefile
  test/conformance/conformance_test.go
  test/e2e/dlq_test.go
Labels: approved, lgtm, size/M

#602 Adds policyInformer to Trigger and Broker controllers
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/controller_test.go
Labels: approved, lgtm, size/S, kind/bug

#606 Limit the resource request for rabbitmq cluster in conformance tests
  test/conformance/resources/rabbitmqcluster/rabbitmqcluster.yaml
Labels: approved, size/XS, lgtm, kind/cleanup

#595 [main] Update actions
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/M

#601 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#597 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/reconciler-test/pkg/environment/logging.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#616 Remove requeue from dispatcher properties in favour of retries
  cmd/dispatcher/main.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
Labels: approved, lgtm, size/M, kind/cleanup

#618 Fix code style issue
  pkg/dispatcher/dispatcher.go
Labels: approved, size/XS, lgtm

#610 Fix tests env in Eventing RabbitMQ
  .github/workflows/knative-style.yaml
  go.mod
  go.sum
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/brokerstandalone/broker_test.go
  test/conformance/conformance_test.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/control_plane.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
