Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-02, with the labels that each got.

#1054 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1053 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1056 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#1057 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/service.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/service.yaml
  vendor/knative.dev/reconciler-test/resources/svc/service.go
  vendor/knative.dev/reconciler-test/resources/svc/service.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1058 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1059 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/pkg/LICENSE
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/knative.dev/reconciler-test/pkg/environment/standard.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/images/file/file.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1060 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1063 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1065 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1066 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/istio.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/environment/standard.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1067 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1068 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1069 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1071 E2E Makes secret patching more resilient.
  test/e2e/rabbitmqcluster.go
Labels: approved, lgtm, size/M, kind/cleanup

#1073 don't stop polling if there is a not found error
  test/e2e/rabbitmqcluster.go
Labels: approved, size/XS, lgtm, kind/cleanup

#1070 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/rabbitmqsource/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1077 adding stop clause to poll inmediate
  test/e2e/rabbitmqcluster.go
Labels: approved, size/XS, lgtm, kind/cleanup

#1075 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1080 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1079 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1084 [release-1.9] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm
