Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-04, with the labels that each got.

#1089 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1094 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1092 upgrade to latest dependencies
  go.mod
  go.sum
  pkg/reconciler/broker/broker_test.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/service.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1096 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#1097 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1098 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1100 chore: migrate from k8s.gcr.io to registry.k8s.io
  config/source/config-observability.yaml
Labels: approved, size/XS, lgtm

#1099 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1102 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#1101 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1103 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1104 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1105 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1108 replaced knative eventing heartbeats location in hack/tools go script imports
  hack/tools.go
  vendor/knative.dev/eventing/cmd/heartbeats/main.go
  vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/M, kind/cleanup

#1115 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#1114 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1116 Fix removed Eventing test images & update deps
  go.mod
  go.sum
  hack/tools.go
  vendor/knative.dev/eventing/cmd/heartbeats/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.go
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/eventing/test/test_images/event-flaker/main.go
  vendor/knative.dev/eventing/test/test_images/event-library/main.go
  vendor/knative.dev/reconciler-test/resources/svc/service.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1120 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
