Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-06, with the labels that each got.

#1139 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1140 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1135 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/XL

#1143 cleanup: update github/make supporting releases to latest versions
  .github/workflows/kind-e2e.yaml
  Makefile
Labels: approved, lgtm, size/M, kind/cleanup

#1141 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1144 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1138 removing non used env var for the receive adapter and old source docs…
  docs/source/README.md
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/source/resources/receive_adapter_test.go
Labels: approved, lgtm, size/M

#1147 fixing bug in name of Solender to avoid CLA troubles, is fixing …
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, lgtm, size/M, kind/bug

#1148 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/broker/eventtypes.go
  vendor/knative.dev/eventing/pkg/broker/metrics.go
  vendor/knative.dev/eventing/pkg/broker/ttl.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1142 cleanup: update github.com/rabbitmq/amqp091-go from 1.3.0 to 1.8.1
  go.mod
  go.sum
  vendor/github.com/rabbitmq/amqp091-go/.golangci.yml
  vendor/github.com/rabbitmq/amqp091-go/.travis.yml
  vendor/github.com/rabbitmq/amqp091-go/CHANGELOG.md
  vendor/github.com/rabbitmq/amqp091-go/CONTRIBUTING.md
  vendor/github.com/rabbitmq/amqp091-go/Makefile
  vendor/github.com/rabbitmq/amqp091-go/README.md
  vendor/github.com/rabbitmq/amqp091-go/RELEASE.md
  vendor/github.com/rabbitmq/amqp091-go/certs.sh
  vendor/github.com/rabbitmq/amqp091-go/change_version.sh
  vendor/github.com/rabbitmq/amqp091-go/channel.go
  vendor/github.com/rabbitmq/amqp091-go/confirms.go
  vendor/github.com/rabbitmq/amqp091-go/connection.go
  vendor/github.com/rabbitmq/amqp091-go/consumers.go
  vendor/github.com/rabbitmq/amqp091-go/doc.go
  vendor/github.com/rabbitmq/amqp091-go/fuzz.go
  vendor/github.com/rabbitmq/amqp091-go/log.go
  vendor/github.com/rabbitmq/amqp091-go/pre-commit
  vendor/github.com/rabbitmq/amqp091-go/read.go
  vendor/github.com/rabbitmq/amqp091-go/spec091.go
  vendor/github.com/rabbitmq/amqp091-go/types.go
  vendor/github.com/rabbitmq/amqp091-go/uri.go
  vendor/github.com/rabbitmq/amqp091-go/write.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup
