Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-09, with the labels that each got.

#1213 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1211 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/openzipkin/zipkin-go/.golangci.yml
  vendor/github.com/openzipkin/zipkin-go/README.md
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1217 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1218 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1219 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1215 Added hard reset conditions to RabbitMQ connections in the Adapter and Dispatcher
  cmd/dispatcher/main.go
  cmd/ingress/main.go
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/rabbit/connections_handler.go
  pkg/rabbit/connections_handler_test.go
Labels: approved, lgtm, size/M

#1221 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1220 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1223 Update dependencies
  go.mod
  go.sum
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/addressable/addressable.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1225 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1227 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1229 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1230 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1231 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1232 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/README.md
  vendor/github.com/benbjohnson/clock/clock.go
  vendor/github.com/benbjohnson/clock/context.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/array.go
  vendor/go.uber.org/zap/array_go118.go
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/error.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/internal/stacktrace/stack.go
  vendor/go.uber.org/zap/internal/ztest/clock.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sink.go
  vendor/go.uber.org/zap/writer.go
  vendor/go.uber.org/zap/zapcore/core.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/lazy_with.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.go
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.yaml
  vendor/knative.dev/eventing/test/rekt/resources/pingsource/pingsource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.yaml
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1234 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1233 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/S, skip-review

#1236 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1238 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L
