Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-08, with the labels that each got.

#1189 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1190 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1191 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#1172 Kind fixes for e2e tests
  Makefile
  test/e2e/kind.yaml
Labels: approved, lgtm, size/S

#1178 Rabbitmq mtls example
  docs/broker/README.md
  docs/prerequisites.md
  docs/source/README.md
  samples/external-cluster/README.md
  samples/multiple-namespaces/README.md
  samples/predeclared-setup/README.md
  samples/quick-setup/README.md
  samples/rabbitmq-mtls/200-rabbitmq.yaml
  samples/rabbitmq-mtls/200-selfsigned-cluster-issuer.yaml
  samples/rabbitmq-mtls/300-certificate.yaml
  samples/rabbitmq-mtls/400-rabbitmq.yaml
  samples/rabbitmq-mtls/500-sink.yaml
  samples/rabbitmq-mtls/README.md
  samples/rabbitmq-mtls/source-files/100-perf-test.yaml
  samples/rabbitmq-mtls/source-files/200-source.yaml
  samples/retry-configuration/README.md
  samples/trigger-customizations/README.md
  test/e2e/config/rabbitmq/cluster.yaml
Labels: approved, lgtm, size/L

#1192 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1195 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1194 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/eventing_tls_feature.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/features/featureflags/featureflags.go
  vendor/knative.dev/eventing/test/rekt/resources/addressable/addressable.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/channel_impl/channel_impl.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.yaml
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/resources/certificate/certificate.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1197 Rename knative-sandbox to knative-extensions
  ADOPTERS.MD
  README.md
  docs/CONTRIBUTING.md
  docs/broker/README.md
  docs/source/README.md
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/source/resources/receive_adapter.go
  pkg/reconciler/trigger/resources/dispatcher.go
  test/e2e/README.md
  test/performance/README.md
Labels: approved, lgtm, size/M

#1196 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1198 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1199 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender_new.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/eventing/pkg/kncloudevents/utils.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/105-certificate-service.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1200 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1202 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1203 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1204 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1205 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1206 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1208 use QueueDeclarePassive to check existing queue
  pkg/adapter/adapter.go
  pkg/rabbit/connections_handler.go
  pkg/rabbit/connections_handler_test.go
  pkg/rabbit/rabbit_mocks.go
Labels: approved, lgtm, size/S, kind/enhancement

#1210 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1212 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L
