Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-11, with the labels that each got.

#1272 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_linux.go
  vendor/github.com/golang/glog/glog_file_other.go
  vendor/github.com/golang/glog/glog_file_posix.go
  vendor/github.com/golang/glog/glog_flags.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/101-rbac.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1273 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1275 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1276 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1277 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1279 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1280 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/parallel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/sequence.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1281 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1282 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1283 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1284 Make SECURITY.md consistent
  SECURITY.md
Labels: approved, size/XS, lgtm

#1285 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v3/jwt/builder.go
  vendor/github.com/go-jose/go-jose/v3/jwt/claims.go
  vendor/github.com/go-jose/go-jose/v3/jwt/doc.go
  vendor/github.com/go-jose/go-jose/v3/jwt/errors.go
  vendor/github.com/go-jose/go-jose/v3/jwt/jwt.go
  vendor/github.com/go-jose/go-jose/v3/jwt/validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/auth/token_provider.go
  vendor/knative.dev/eventing/pkg/auth/utils.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/state/timings.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1290 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1288 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/containersource.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1289 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1293 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1296 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1294 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1297 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review
