Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-01, with the labels that each got.

#1032 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1033 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/deployment.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1034 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1036 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1035 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/sql/v2/parser/expression_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/utils/casting.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/abuse_protection.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/resources/channel/channel.go
  vendor/knative.dev/eventing/test/rekt/resources/channel/channel.yaml
  vendor/knative.dev/eventing/test/rekt/resources/channel_impl/channel_impl.go
  vendor/knative.dev/eventing/test/rekt/resources/channel_impl/channel_impl.yaml
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.yaml
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1037 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1040 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1041 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1039 Changed rabbitmq operators version on makefile to generate envs
  Makefile
Labels: approved, size/XS, lgtm

#1047 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1046 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/trigger_sink_resolution.go
  vendor/knative.dev/eventing/test/rekt/resources/channel_impl/channel_impl.go
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/README.md
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.go
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1049 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/apiserversouce.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1050 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1051 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L
