Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-05, with the labels that each got.

#1122 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1119 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1124 Fix update deps 121
  go.mod
  go.sum
  pkg/reconciler/trigger/trigger_test.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1beta2/eventtype.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1beta2/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta2/eventtype.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta2/expansion_generated.go
  vendor/knative.dev/eventing/pkg/metrics/source/stats_reporter.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/reconciler-test/cmd/eventshub/main.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/102-service.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/104-forwarder.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_log.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub_image.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/resources/knativeservice/ksvc.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1126 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1129 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1130 Fix addressable unit tests
  go.mod
  go.sum
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/knative.dev/eventing/pkg/eventingtls/servermanager.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/pingsource.go
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/timing.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_log.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1134 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1136 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
