Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-12, with the labels that each got.

#1299 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1303 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1302 Fix missing name key in samples/external-cluster/README.md
  samples/external-cluster/README.md
Labels: approved, size/XS, lgtm

#1301 Fix missing colon in source/README.md
  docs/source/README.md
Labels: approved, size/XS, lgtm

#1305 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#1291 Dependabot go jose fixes
  Makefile
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1306 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/cmd/heartbeats/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1308 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/token_verifier.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1309 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1312 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1313 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1314 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1315 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review
