Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-07, with the labels that each got.

#1160 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1153 improved readbinary method
  pkg/rabbit/message.go
  pkg/rabbit/message_test.go
Labels: approved, lgtm, size/M

#1165 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1164 Improving flaky tests
  Makefile
  pkg/rabbit/message.go
  test/e2e/broker_test.go
  test/e2e/config/certsecret/certsecret.go
  test/e2e/config/certsecret/secret.yaml
  test/e2e/config/rabbitmq/cluster.yaml
  test/e2e/config/rabbitmq/rabbitmq.go
  test/e2e/config/rabbitmqvhost/clustervhost.yaml
  test/e2e/config/rabbitmqvhost/rabbitmqvhost.go
  test/e2e/main_test.go
  test/e2e/rabbitmqcluster.go
  test/e2e/selfsignedcerts.go
  test/e2e/source_test.go
Labels: approved, lgtm, size/L, kind/cleanup

#1167 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1169 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1170 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1174 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1171 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1173 Fixed wrong Source's webhook service yaml definition
  config/source/400-webhook-service.yaml
Labels: approved, lgtm, size/S, kind/bug

#1176 Remove deprecated HTTPMessageSender usage
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
Labels: approved, lgtm, size/M

#1177 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1184 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1183 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1186 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1163 Delivery failure
  cmd/dispatcher/main.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/rabbit/connections_handler_test.go
  pkg/rabbit/rabbit_mocks.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/dispatcher.go
  pkg/reconciler/broker/resources/dispatcher_test.go
  pkg/reconciler/trigger/resources/dispatcher.go
  pkg/reconciler/trigger/resources/dispatcher_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, lgtm, size/XL, kind/enhancement
