Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2023-10, with the labels that each got.

#1240 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1241 Support triggers `OIDCIdentityCreated` condition type
  go.mod
  go.sum
  pkg/reconciler/trigger/trigger_test.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/istio_quit.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1242 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1244 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1243 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1247 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1249 updated x/net to v0.17 to fix cve-2023-44487
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1248 Update dependencies
  cmd/receive_adapter/main.go
  go.mod
  go.sum
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  third_party/VENDOR-LICENSE/github.com/coreos/go-oidc/v3/oidc/LICENSE
  third_party/VENDOR-LICENSE/github.com/coreos/go-oidc/v3/oidc/NOTICE
  third_party/VENDOR-LICENSE/github.com/go-jose/go-jose/v3/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-jose/go-jose/v3/json/LICENSE
  third_party/VENDOR-LICENSE/golang.org/x/crypto/pbkdf2/LICENSE
  vendor/github.com/coreos/go-oidc/v3/LICENSE
  vendor/github.com/coreos/go-oidc/v3/NOTICE
  vendor/github.com/coreos/go-oidc/v3/oidc/jose.go
  vendor/github.com/coreos/go-oidc/v3/oidc/jwks.go
  vendor/github.com/coreos/go-oidc/v3/oidc/oidc.go
  vendor/github.com/coreos/go-oidc/v3/oidc/verify.go
  vendor/github.com/go-jose/go-jose/v3/.gitignore
  vendor/github.com/go-jose/go-jose/v3/.golangci.yml
  vendor/github.com/go-jose/go-jose/v3/.travis.yml
  vendor/github.com/go-jose/go-jose/v3/BUG-BOUNTY.md
  vendor/github.com/go-jose/go-jose/v3/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v3/LICENSE
  vendor/github.com/go-jose/go-jose/v3/README.md
  vendor/github.com/go-jose/go-jose/v3/asymmetric.go
  vendor/github.com/go-jose/go-jose/v3/cipher/cbc_hmac.go
  vendor/github.com/go-jose/go-jose/v3/cipher/concat_kdf.go
  vendor/github.com/go-jose/go-jose/v3/cipher/ecdh_es.go
  vendor/github.com/go-jose/go-jose/v3/cipher/key_wrap.go
  vendor/github.com/go-jose/go-jose/v3/crypter.go
  vendor/github.com/go-jose/go-jose/v3/doc.go
  vendor/github.com/go-jose/go-jose/v3/encoding.go
  vendor/github.com/go-jose/go-jose/v3/json/LICENSE
  vendor/github.com/go-jose/go-jose/v3/json/README.md
  vendor/github.com/go-jose/go-jose/v3/json/decode.go
  vendor/github.com/go-jose/go-jose/v3/json/encode.go
  vendor/github.com/go-jose/go-jose/v3/json/indent.go
  vendor/github.com/go-jose/go-jose/v3/json/scanner.go
  vendor/github.com/go-jose/go-jose/v3/json/stream.go
  vendor/github.com/go-jose/go-jose/v3/json/tags.go
  vendor/github.com/go-jose/go-jose/v3/jwe.go
  vendor/github.com/go-jose/go-jose/v3/jwk.go
  vendor/github.com/go-jose/go-jose/v3/jws.go
  vendor/github.com/go-jose/go-jose/v3/opaque.go
  vendor/github.com/go-jose/go-jose/v3/shared.go
  vendor/github.com/go-jose/go-jose/v3/signing.go
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/auth/audience.go
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/knative.dev/eventing/pkg/auth/token_provider.go
  vendor/knative.dev/eventing/pkg/auth/token_verifier.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/manifest/manifest.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1254 Update dependencies
  go.mod
  go.sum
  test/e2e/broker_test.go
  test/e2e/source_test.go
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/data_plane.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/resources/serviceaccount/serviceaccount.go
  vendor/knative.dev/reconciler-test/pkg/resources/serviceaccount/serviceaccount.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1256 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1255 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/apiserversouce.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/test/rekt/resources/pingsource/pingsource.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1257 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1239 removing parse url from the get rabbitmqUrl function
  pkg/rabbit/exchange.go
  pkg/rabbit/secret_test.go
  pkg/rabbit/service.go
  pkg/rabbit/service_test.go
  pkg/rabbit/types.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/source/rabbitmqsource.go
Labels: approved, lgtm, size/M, kind/bug

#1260 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/token_provider.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1258 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1261 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/utils.go
  vendor/knative.dev/eventing/test/rekt/resources/addressable/addressable.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/channel_impl/channel_impl.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1262 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/pingsource.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1264 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1266 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1267 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1268 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1269 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#1270 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1271 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1265 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/eventing_tls_feature.go
  vendor/knative.dev/eventing/test/rekt/features/featureflags/featureflags.go
  vendor/knative.dev/eventing/test/rekt/resources/addressable/addressable.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/channel_impl/channel_impl.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.yaml
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/knative.dev/reconciler-test/resources/certificate/certificate.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL
