Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2024-01, with the labels that each got.

#1316 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1317 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1318 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1319 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1321 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1320 bump k8s version and other CI stuff
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/M

#1322 eventing-rabbitmq-approvers should be tagged for reviews
  OWNERS
Labels: approved, size/XS, lgtm

#1323 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#1326 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1328 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1327 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/coreos/go-oidc/v3/oidc/jwks.go
  vendor/github.com/coreos/go-oidc/v3/oidc/oidc.go
  vendor/github.com/coreos/go-oidc/v3/oidc/verify.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/common/model/alert.go
  vendor/github.com/prometheus/common/model/metadata.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/github.com/prometheus/common/model/signature.go
  vendor/github.com/prometheus/common/model/silence.go
  vendor/github.com/prometheus/common/model/value.go
  vendor/github.com/prometheus/common/model/value_float.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/google.golang.org/protobuf/encoding/protodelim/protodelim.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1330 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1331 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1332 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1333 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.go
  vendor/knative.dev/eventing/test/rekt/resources/pingsource/pingsource.go
  vendor/knative.dev/eventing/test/rekt/resources/pingsource/pingsource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1334 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1335 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1337 Update Golang in go.mod to 1.21
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#1336 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/knative.dev/eventing/pkg/metrics/metrics.go
  vendor/knative.dev/eventing/pkg/metrics/source/stats_reporter.go
  vendor/knative.dev/eventing/test/rekt/features/featureflags/featureflags.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1339 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1340 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1341 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review
