Repository knative-extensions/eventing-rabbitmq, pull requests merged in 2025-04, with the labels that each got.

#1548 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1549 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1550 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1551 Migrate golanglint-ci config to v2
  .golangci.yaml
Labels: approved, lgtm, size/M

#1541 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/conformance/pkg/event/event.go
  vendor/github.com/cloudevents/conformance/pkg/event/read.go
  vendor/github.com/cloudevents/conformance/pkg/event/write.go
  vendor/github.com/cloudevents/conformance/pkg/http/http.go
  vendor/github.com/cloudevents/conformance/pkg/http/raw.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/h2c/h2c.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/knative.dev/eventing/pkg/apis/common/integration/v1alpha1/aws.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/integration_sink_lifecycle.go
  vendor/knative.dev/hack/boilerplate.go.txt
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1552 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#1553 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/types/typeutil/callee.go
  vendor/golang.org/x/tools/internal/event/label/label.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/modindex/lookup.go
  vendor/golang.org/x/tools/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/typeparams/free.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/golang.org/x/tools/internal/typesinternal/classify_call.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1554 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1555 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1556 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, skip-review

#1558 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1561 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1560 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1562 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: skip-review

#1563 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1564 [Automated] Update eventing-rabbitmq-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#1565 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/endpointsharding/endpointsharding.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/transport/client_stream.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/server_stream.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL
